/* The following code was generated by JFlex 1.7.0 */

package fr.loria.k.revisor.engine.revisorPCSFC.console.parser;

import java_cup.runtime.Symbol;
import fr.loria.orpailleur.revisor.engine.core.console.exception.LexerException;

/**
 * This is Revisor PCSFC's console lexer.
 * @author Matthias Bertrand
 */

public class PCSFCConsoleLexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int FILE = 2;
  public static final int CONSTROPERS = 4;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1,  1,  2, 2
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\5\1\2\1\4\1\4\1\3\22\0\1\5\1\16\1\24"+
    "\1\1\2\0\1\23\1\0\1\50\1\51\1\0\1\21\1\47\1\6"+
    "\1\10\1\0\12\7\1\46\1\25\1\17\1\15\1\20\2\0\4\22"+
    "\1\14\14\22\1\12\1\22\1\11\1\13\5\22\3\0\1\23\1\22"+
    "\1\0\1\34\1\44\1\42\1\52\1\31\1\36\1\32\1\22\1\26"+
    "\2\22\1\35\1\40\1\27\1\37\1\53\1\22\1\33\1\43\1\30"+
    "\1\41\1\45\4\22\1\0\1\23\10\0\1\4\32\0\1\5\u15df\0"+
    "\1\5\u097f\0\13\5\35\0\1\4\1\4\5\0\1\5\57\0\1\5"+
    "\u0fa0\0\1\5\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\ud00f\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\3\0\1\1\1\2\1\3\2\4\1\1\2\5\1\6"+
    "\1\7\2\10\1\11\1\1\1\12\7\5\1\13\1\14"+
    "\1\15\1\16\1\5\1\17\1\20\1\21\1\1\2\22"+
    "\1\23\1\24\1\25\1\26\1\27\1\30\1\2\1\0"+
    "\1\4\1\5\2\10\1\0\10\5\1\31\1\5\1\0"+
    "\2\22\1\32\1\5\1\33\12\5\1\34\1\5\1\35"+
    "\1\36\1\5\1\37\10\5\1\40\1\41\3\5\1\42"+
    "\3\5\1\43\1\44\1\45\2\5\1\46";

  private static int [] zzUnpackAction() {
    int [] result = new int[104];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\54\0\130\0\204\0\260\0\204\0\334\0\u0108"+
    "\0\u0134\0\u0160\0\u018c\0\u01b8\0\u01e4\0\u0210\0\u01e4\0\204"+
    "\0\u023c\0\204\0\u0268\0\u0294\0\u02c0\0\u02ec\0\u0318\0\u0344"+
    "\0\u0370\0\u039c\0\204\0\204\0\204\0\u03c8\0\u03f4\0\204"+
    "\0\u0420\0\u044c\0\u0478\0\u044c\0\204\0\204\0\u04a4\0\204"+
    "\0\204\0\204\0\204\0\u0134\0\u0134\0\u04d0\0\204\0\u04fc"+
    "\0\u0528\0\u0554\0\u0580\0\u05ac\0\u05d8\0\u0604\0\u0630\0\u065c"+
    "\0\u0688\0\204\0\u06b4\0\u03f4\0\204\0\u06e0\0\204\0\u070c"+
    "\0\204\0\u0738\0\u0764\0\u0790\0\u07bc\0\u07e8\0\u0814\0\u0840"+
    "\0\u086c\0\u0898\0\u08c4\0\u018c\0\u08f0\0\u018c\0\u018c\0\u091c"+
    "\0\u018c\0\u0948\0\u0974\0\u09a0\0\u09cc\0\u09f8\0\u0a24\0\u0a50"+
    "\0\u0a7c\0\u018c\0\u018c\0\u0aa8\0\u0ad4\0\u0b00\0\u018c\0\u0b2c"+
    "\0\u0b58\0\u0b84\0\u018c\0\u018c\0\u018c\0\u0bb0\0\u0bdc\0\u018c";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[104];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\4\1\5\4\6\1\7\1\10\1\11\1\12\3\13"+
    "\1\14\1\15\1\16\1\17\1\4\1\13\1\20\1\21"+
    "\1\22\1\23\1\13\1\12\1\24\1\13\1\25\1\13"+
    "\1\26\1\27\3\13\1\30\1\13\1\31\1\13\1\32"+
    "\1\33\1\34\1\35\1\13\1\36\2\37\4\6\46\37"+
    "\2\4\4\6\1\40\6\4\1\41\1\42\1\43\1\44"+
    "\1\40\1\4\1\45\1\4\1\46\20\4\1\47\1\50"+
    "\1\51\1\52\2\4\54\0\2\5\1\53\2\0\47\5"+
    "\7\0\1\10\1\54\52\0\1\10\1\55\52\0\1\55"+
    "\53\0\1\13\1\0\1\13\1\56\2\13\5\0\1\13"+
    "\3\0\5\13\1\56\12\13\4\0\2\13\7\0\1\13"+
    "\1\0\4\13\5\0\1\13\3\0\20\13\4\0\2\13"+
    "\15\0\1\57\2\0\1\20\50\0\1\57\53\0\1\60"+
    "\45\0\1\61\1\0\4\61\5\0\1\61\3\0\20\61"+
    "\4\0\2\61\7\0\1\13\1\0\4\13\5\0\1\13"+
    "\3\0\1\13\1\62\16\13\4\0\2\13\7\0\1\13"+
    "\1\0\4\13\5\0\1\13\3\0\1\13\1\63\16\13"+
    "\4\0\2\13\7\0\1\13\1\0\4\13\5\0\1\13"+
    "\3\0\3\13\1\64\14\13\4\0\2\13\7\0\1\13"+
    "\1\0\4\13\5\0\1\13\3\0\11\13\1\65\6\13"+
    "\4\0\2\13\7\0\1\13\1\0\4\13\5\0\1\13"+
    "\3\0\11\13\1\66\6\13\4\0\2\13\7\0\1\13"+
    "\1\0\4\13\5\0\1\13\3\0\7\13\1\67\1\13"+
    "\1\70\6\13\4\0\2\13\7\0\1\13\1\0\4\13"+
    "\5\0\1\13\3\0\11\13\1\71\6\13\4\0\2\13"+
    "\15\0\1\72\45\0\1\13\1\0\4\13\5\0\1\13"+
    "\3\0\5\13\1\73\12\13\4\0\2\13\2\37\2\0"+
    "\2\74\46\37\15\0\1\75\2\0\1\45\50\0\1\75"+
    "\53\0\1\76\53\0\1\77\45\0\1\13\1\0\2\13"+
    "\1\100\1\13\5\0\1\13\3\0\13\13\1\100\4\13"+
    "\4\0\2\13\20\0\1\20\42\0\1\61\1\0\4\61"+
    "\5\0\1\61\1\0\1\101\1\0\20\61\4\0\2\61"+
    "\7\0\1\13\1\0\4\13\5\0\1\13\3\0\2\13"+
    "\1\102\15\13\4\0\2\13\7\0\1\13\1\0\4\13"+
    "\5\0\1\13\3\0\13\13\1\103\4\13\4\0\2\13"+
    "\7\0\1\13\1\0\4\13\5\0\1\13\3\0\6\13"+
    "\1\104\10\13\1\105\4\0\2\13\7\0\1\13\1\0"+
    "\4\13\5\0\1\13\3\0\6\13\1\106\11\13\4\0"+
    "\2\13\7\0\1\13\1\0\4\13\5\0\1\13\3\0"+
    "\5\13\1\107\12\13\4\0\2\13\7\0\1\13\1\0"+
    "\4\13\5\0\1\13\3\0\3\13\1\110\14\13\4\0"+
    "\2\13\7\0\1\13\1\0\4\13\5\0\1\13\3\0"+
    "\1\13\1\111\16\13\4\0\2\13\7\0\1\13\1\0"+
    "\4\13\5\0\1\13\3\0\11\13\1\112\6\13\4\0"+
    "\2\13\7\0\1\13\1\0\4\13\5\0\1\13\3\0"+
    "\1\113\17\13\4\0\2\13\20\0\1\45\42\0\1\13"+
    "\1\0\3\13\1\114\5\0\1\13\3\0\3\13\1\114"+
    "\14\13\4\0\2\13\7\0\1\13\1\0\4\13\5\0"+
    "\1\13\3\0\3\13\1\115\14\13\4\0\2\13\7\0"+
    "\1\13\1\0\4\13\5\0\1\13\3\0\12\13\1\116"+
    "\5\13\4\0\2\13\7\0\1\13\1\0\4\13\5\0"+
    "\1\13\3\0\7\13\1\117\10\13\4\0\2\13\7\0"+
    "\1\13\1\0\4\13\5\0\1\13\3\0\1\120\17\13"+
    "\4\0\2\13\7\0\1\13\1\0\4\13\5\0\1\13"+
    "\3\0\20\13\4\0\1\121\1\13\7\0\1\13\1\0"+
    "\4\13\5\0\1\13\3\0\12\13\1\122\5\13\4\0"+
    "\2\13\7\0\1\13\1\0\4\13\5\0\1\13\3\0"+
    "\6\13\1\123\11\13\4\0\2\13\7\0\1\13\1\0"+
    "\4\13\5\0\1\13\3\0\15\13\1\124\2\13\4\0"+
    "\2\13\7\0\1\13\1\0\4\13\5\0\1\13\3\0"+
    "\7\13\1\125\10\13\4\0\2\13\7\0\1\13\1\0"+
    "\4\13\5\0\1\13\3\0\1\13\1\126\16\13\4\0"+
    "\2\13\7\0\1\13\1\0\4\13\5\0\1\13\3\0"+
    "\4\13\1\127\13\13\4\0\2\13\7\0\1\13\1\0"+
    "\4\13\5\0\1\13\3\0\15\13\1\130\2\13\4\0"+
    "\2\13\7\0\1\13\1\0\4\13\5\0\1\13\3\0"+
    "\13\13\1\131\4\13\4\0\2\13\7\0\1\13\1\0"+
    "\4\13\5\0\1\13\3\0\5\13\1\132\12\13\4\0"+
    "\2\13\7\0\1\13\1\0\4\13\5\0\1\13\3\0"+
    "\2\13\1\133\15\13\4\0\2\13\7\0\1\13\1\0"+
    "\4\13\5\0\1\13\3\0\3\13\1\134\14\13\4\0"+
    "\2\13\7\0\1\13\1\0\4\13\5\0\1\13\3\0"+
    "\2\13\1\135\15\13\4\0\2\13\7\0\1\13\1\0"+
    "\4\13\5\0\1\13\3\0\3\13\1\136\14\13\4\0"+
    "\2\13\7\0\1\13\1\0\4\13\5\0\1\13\3\0"+
    "\3\13\1\137\14\13\4\0\2\13\7\0\1\13\1\0"+
    "\4\13\5\0\1\13\3\0\7\13\1\140\10\13\4\0"+
    "\2\13\7\0\1\13\1\0\4\13\5\0\1\13\3\0"+
    "\6\13\1\141\11\13\4\0\2\13\7\0\1\13\1\0"+
    "\4\13\5\0\1\13\3\0\17\13\1\142\4\0\2\13"+
    "\7\0\1\13\1\0\4\13\5\0\1\13\3\0\5\13"+
    "\1\143\12\13\4\0\2\13\7\0\1\13\1\0\4\13"+
    "\5\0\1\13\3\0\6\13\1\144\11\13\4\0\2\13"+
    "\7\0\1\13\1\0\4\13\5\0\1\13\3\0\1\13"+
    "\1\145\16\13\4\0\2\13\7\0\1\13\1\0\4\13"+
    "\5\0\1\13\3\0\6\13\1\146\11\13\4\0\2\13"+
    "\7\0\1\13\1\0\4\13\5\0\1\13\3\0\5\13"+
    "\1\147\12\13\4\0\2\13\7\0\1\13\1\0\4\13"+
    "\5\0\1\13\3\0\15\13\1\150\2\13\4\0\2\13";

  private static int [] zzUnpackTrans() {
    int [] result = new int[3080];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\3\0\1\11\1\1\1\11\11\1\1\11\1\1\1\11"+
    "\10\1\3\11\2\1\1\11\4\1\2\11\1\1\4\11"+
    "\1\0\2\1\1\11\1\1\1\0\10\1\1\11\1\1"+
    "\1\0\1\11\1\1\1\11\1\1\1\11\47\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[104];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true iff the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true iff the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
  StringBuffer string = new StringBuffer();
  
  private Symbol symbol(int type) {
	return new Symbol(type, this.yyline, this.yycolumn);
  }

  private Symbol symbol(int type, Object value) {
	return new Symbol(type, this.yyline, this.yycolumn, value);
  }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public PCSFCConsoleLexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 198) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public Symbol next_token() throws java.io.IOException, LexerException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          {     return symbol(PCSFCConsoleSymbols.EOF);
 }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { throw new LexerException("Illegal character '" + yytext() + "'.", null, true, false);
            } 
            // fall through
          case 39: break;
          case 2: 
            { /* This is a comment, therefore we do nothing */
            } 
            // fall through
          case 40: break;
          case 3: 
            { /* Just skip what was found, do nothing */
            } 
            // fall through
          case 41: break;
          case 4: 
            { return symbol(PCSFCConsoleSymbols.REAL, yytext());
            } 
            // fall through
          case 42: break;
          case 5: 
            { yybegin(CONSTROPERS); return symbol(PCSFCConsoleSymbols.IDENTIFIER, yytext());
            } 
            // fall through
          case 43: break;
          case 6: 
            { return symbol(PCSFCConsoleSymbols.SIMPLE_EQUAL);
            } 
            // fall through
          case 44: break;
          case 7: 
            { return symbol(PCSFCConsoleSymbols.NEGATIVE_FORMULA_SYMBOL);
            } 
            // fall through
          case 45: break;
          case 8: 
            { return symbol(PCSFCConsoleSymbols.CONSTRAINT_OPERATOR, yytext());
            } 
            // fall through
          case 46: break;
          case 9: 
            { return symbol(PCSFCConsoleSymbols.BINARY_FORMULA_OPERATOR, yytext());
            } 
            // fall through
          case 47: break;
          case 10: 
            { return symbol(PCSFCConsoleSymbols.END_OF_INSTRUCTION, yytext());
            } 
            // fall through
          case 48: break;
          case 11: 
            { return symbol(PCSFCConsoleSymbols.COLON);
            } 
            // fall through
          case 49: break;
          case 12: 
            { return symbol(PCSFCConsoleSymbols.COMMA);
            } 
            // fall through
          case 50: break;
          case 13: 
            { return symbol(PCSFCConsoleSymbols.OPENING_PARENTHESIS);
            } 
            // fall through
          case 51: break;
          case 14: 
            { return symbol(PCSFCConsoleSymbols.CLOSING_PARENTHESIS);
            } 
            // fall through
          case 52: break;
          case 15: 
            { return symbol(PCSFCConsoleSymbols.FILE, yytext());
            } 
            // fall through
          case 53: break;
          case 16: 
            { yybegin(YYINITIAL); return symbol(PCSFCConsoleSymbols.CONSTRAINT_TERM_OPERATOR, yytext());
            } 
            // fall through
          case 54: break;
          case 17: 
            { yybegin(YYINITIAL); return symbol(PCSFCConsoleSymbols.SIMPLE_EQUAL);
            } 
            // fall through
          case 55: break;
          case 18: 
            { yybegin(YYINITIAL); return symbol(PCSFCConsoleSymbols.CONSTRAINT_OPERATOR, yytext());
            } 
            // fall through
          case 56: break;
          case 19: 
            { yybegin(YYINITIAL); return symbol(PCSFCConsoleSymbols.BINARY_FORMULA_OPERATOR, yytext());
            } 
            // fall through
          case 57: break;
          case 20: 
            { yybegin(YYINITIAL); return symbol(PCSFCConsoleSymbols.END_OF_INSTRUCTION, yytext());
            } 
            // fall through
          case 58: break;
          case 21: 
            { yybegin(YYINITIAL); return symbol(PCSFCConsoleSymbols.COLON);
            } 
            // fall through
          case 59: break;
          case 22: 
            { yybegin(YYINITIAL); return symbol(PCSFCConsoleSymbols.COMMA);
            } 
            // fall through
          case 60: break;
          case 23: 
            { yybegin(YYINITIAL); return symbol(PCSFCConsoleSymbols.OPENING_PARENTHESIS);
            } 
            // fall through
          case 61: break;
          case 24: 
            { yybegin(YYINITIAL); return symbol(PCSFCConsoleSymbols.CLOSING_PARENTHESIS);
            } 
            // fall through
          case 62: break;
          case 25: 
            { return symbol(PCSFCConsoleSymbols.ASSIGNMENT_OPERATOR);
            } 
            // fall through
          case 63: break;
          case 26: 
            { yybegin(YYINITIAL); return symbol(PCSFCConsoleSymbols.ASSIGNMENT_OPERATOR);
            } 
            // fall through
          case 64: break;
          case 27: 
            { return symbol(PCSFCConsoleSymbols.MODALITY, yytext());
            } 
            // fall through
          case 65: break;
          case 28: 
            { return symbol(PCSFCConsoleSymbols.TAUTOLOGY_FORMULA, yytext());
            } 
            // fall through
          case 66: break;
          case 29: 
            { return symbol(PCSFCConsoleSymbols.ENUM_DECLARATION_KEYWORD);
            } 
            // fall through
          case 67: break;
          case 30: 
            { return symbol(PCSFCConsoleSymbols.REAL_DECLARATION_KEYWORD);
            } 
            // fall through
          case 68: break;
          case 31: 
            { yybegin(FILE); return symbol(PCSFCConsoleSymbols.LOAD);
            } 
            // fall through
          case 69: break;
          case 32: 
            { return symbol(PCSFCConsoleSymbols.CLEAR);
            } 
            // fall through
          case 70: break;
          case 33: 
            { return symbol(PCSFCConsoleSymbols.CONST_DECLARATION_KEYWORD);
            } 
            // fall through
          case 71: break;
          case 34: 
            { return symbol(PCSFCConsoleSymbols.REVISE_KEYWORD);
            } 
            // fall through
          case 72: break;
          case 35: 
            { return symbol(PCSFCConsoleSymbols.INTEGER_DECLARATION_KEYWORD);
            } 
            // fall through
          case 73: break;
          case 36: 
            { return symbol(PCSFCConsoleSymbols.FORMULA_DECLARATION_KEYWORD);
            } 
            // fall through
          case 74: break;
          case 37: 
            { return symbol(PCSFCConsoleSymbols.BOOLEAN_DECLARATION_KEYWORD);
            } 
            // fall through
          case 75: break;
          case 38: 
            { return symbol(PCSFCConsoleSymbols.PRINTVARS);
            } 
            // fall through
          case 76: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
