
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package fr.loria.k.revisor.engine.revisorPCSFC.console.parser;

import java_cup.runtime.Scanner;
import java_cup.runtime.Symbol;
import java_cup.runtime.SymbolFactory;
import java.util.ArrayList;
import fr.loria.orpailleur.revisor.engine.core.console.exception.ParserException;
import fr.loria.orpailleur.revisor.engine.core.console.formula.Formula;
import fr.loria.orpailleur.revisor.engine.core.console.instruction.Clear;
import fr.loria.orpailleur.revisor.engine.core.console.instruction.Display;
import fr.loria.orpailleur.revisor.engine.core.console.instruction.Instruction;
import fr.loria.orpailleur.revisor.engine.core.console.instruction.Load;
import fr.loria.k.revisor.engine.revisorPCSFC.console.RevisorConsolePCSFC;
import fr.loria.k.revisor.engine.revisorPCSFC.console.formula.*;
import fr.loria.k.revisor.engine.revisorPCSFC.console.instruction.*;
import fr.loria.k.revisor.engine.revisorPCSFC.pcsfc.*;
import fr.loria.k.revisor.engine.revisorPCSFC.console.formula.constraint.*;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class PCSFCConsoleParser extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return PCSFCConsoleSymbols.class;
}

  /** Default constructor. */
  @Deprecated
  public PCSFCConsoleParser() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public PCSFCConsoleParser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public PCSFCConsoleParser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\066\000\002\002\004\000\002\002\004\000\002\002" +
    "\003\000\002\002\003\000\002\002\003\000\002\002\003" +
    "\000\002\003\003\000\002\003\003\000\002\003\003\000" +
    "\002\003\003\000\002\003\003\000\002\003\003\000\002" +
    "\014\004\000\002\015\003\000\002\016\003\000\002\017" +
    "\003\000\002\004\003\000\002\004\003\000\002\004\003" +
    "\000\002\004\003\000\002\004\003\000\002\004\003\000" +
    "\002\005\005\000\002\006\005\000\002\007\005\000\002" +
    "\010\006\000\002\012\005\000\002\013\007\000\002\021" +
    "\005\000\002\021\003\000\002\020\005\000\002\020\003" +
    "\000\002\011\005\000\002\022\003\000\002\022\003\000" +
    "\002\023\012\000\002\023\012\000\002\024\005\000\002" +
    "\024\004\000\002\024\005\000\002\024\007\000\002\024" +
    "\006\000\002\024\003\000\002\025\003\000\002\025\005" +
    "\000\002\025\003\000\002\025\003\000\002\026\005\000" +
    "\002\027\003\000\002\030\005\000\002\030\003\000\002" +
    "\031\004\000\002\031\003\000\002\032\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\125\000\016\004\020\006\004\012\007\020\006\032" +
    "\012\035\017\001\002\000\006\002\ufff4\011\ufff4\001\002" +
    "\000\004\011\uffed\001\002\000\004\012\125\001\002\000" +
    "\014\002\ufff2\007\uffe2\010\uffe2\011\ufff2\014\052\001\002" +
    "\000\006\007\044\010\043\001\002\000\004\011\042\001" +
    "\002\000\006\002\ufff3\011\ufff3\001\002\000\006\002\ufffe" +
    "\011\ufff8\001\002\000\004\011\ufff1\001\002\000\004\002" +
    "\041\001\002\000\006\002\ufffc\011\ufff6\001\002\000\004" +
    "\012\032\001\002\000\004\005\031\001\002\000\004\011" +
    "\uffee\001\002\000\004\011\uffec\001\002\000\004\011\ufffb" +
    "\001\002\000\006\002\ufffd\011\ufff7\001\002\000\004\011" +
    "\uffef\001\002\000\004\011\ufffa\001\002\000\006\002\uffff" +
    "\011\ufff9\001\002\000\004\011\ufff0\001\002\000\006\002" +
    "\ufff5\011\ufff5\001\002\000\004\026\033\001\002\000\004" +
    "\034\035\001\002\000\006\010\036\027\037\001\002\000" +
    "\006\010\uffe4\027\uffe4\001\002\000\004\034\040\001\002" +
    "\000\004\011\uffe6\001\002\000\006\010\uffe5\027\uffe5\001" +
    "\002\000\004\002\001\001\002\000\004\002\000\001\002" +
    "\000\004\012\051\001\002\000\012\015\045\016\046\017" +
    "\050\033\047\001\002\000\004\011\uffeb\001\002\000\004" +
    "\011\uffea\001\002\000\004\011\uffe7\001\002\000\004\011" +
    "\uffe9\001\002\000\006\007\uffe3\010\uffe3\001\002\000\016" +
    "\012\064\021\061\022\065\025\060\026\053\030\063\001" +
    "\002\000\014\012\064\021\061\022\065\026\053\030\063" +
    "\001\002\000\006\011\uffdf\031\102\001\002\000\004\011" +
    "\uffe1\001\002\000\010\011\uffd6\027\uffd6\031\uffd6\001\002" +
    "\000\006\023\uffcf\024\uffcf\001\002\000\004\026\112\001" +
    "\002\000\004\012\111\001\002\000\004\011\uffe0\001\002" +
    "\000\014\012\064\021\061\022\065\026\053\030\063\001" +
    "\002\000\016\011\uffd4\013\077\023\uffcd\024\uffcd\027\uffd4" +
    "\031\uffd4\001\002\000\010\011\uffd3\027\uffd3\031\uffd3\001" +
    "\002\000\004\023\074\001\002\000\010\011\uffd7\027\uffd7" +
    "\031\uffd7\001\002\000\006\023\uffd1\024\071\001\002\000" +
    "\006\012\073\021\061\001\002\000\006\023\uffd0\024\uffd0" +
    "\001\002\000\006\023\uffcd\024\uffcd\001\002\000\004\021" +
    "\076\001\002\000\010\011\uffd2\027\uffd2\031\uffd2\001\002" +
    "\000\010\011\uffcc\027\uffcc\031\uffcc\001\002\000\004\034" +
    "\100\001\002\000\010\011\uffd5\027\uffd5\031\uffd5\001\002" +
    "\000\010\011\uffdb\027\uffdb\031\uffdb\001\002\000\014\012" +
    "\064\021\061\022\065\026\103\030\104\001\002\000\014" +
    "\012\064\021\061\022\065\026\053\030\063\001\002\000" +
    "\014\012\064\021\061\022\065\026\053\030\063\001\002" +
    "\000\010\011\uffda\027\uffda\031\uffda\001\002\000\010\011" +
    "\uffd8\027\uffd8\031\uffd8\001\002\000\006\027\110\031\102" +
    "\001\002\000\010\011\uffd9\027\uffd9\031\uffd9\001\002\000" +
    "\006\023\uffce\024\uffce\001\002\000\004\012\113\001\002" +
    "\000\004\010\114\001\002\000\004\012\115\001\002\000" +
    "\004\010\116\001\002\000\006\012\120\021\117\001\002" +
    "\000\004\027\122\001\002\000\004\027\121\001\002\000" +
    "\004\011\uffde\001\002\000\004\011\uffdd\001\002\000\006" +
    "\027\124\031\102\001\002\000\010\011\uffdc\027\uffdc\031" +
    "\uffdc\001\002\000\004\013\126\001\002\000\004\021\127" +
    "\001\002\000\004\011\uffe8\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\125\000\040\002\014\003\010\004\022\005\013\006" +
    "\027\007\024\010\020\011\025\012\004\013\021\014\026" +
    "\015\012\016\023\017\015\020\007\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\021\033\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\022\022\054\023" +
    "\061\024\053\025\066\026\055\027\065\030\067\031\056" +
    "\001\001\000\016\024\122\025\066\026\055\027\065\030" +
    "\067\031\056\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\016\024\100\025\066" +
    "\026\055\027\065\030\067\031\056\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\031\071\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\032\074\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\014\025\104\026\055\027\065" +
    "\030\067\031\056\001\001\000\016\024\106\025\066\026" +
    "\055\027\065\030\067\031\056\001\001\000\016\024\105" +
    "\025\066\026\055\027\065\030\067\031\056\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$PCSFCConsoleParser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$PCSFCConsoleParser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$PCSFCConsoleParser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



	
	// Fields :
	
	private RevisorConsolePCSFC console;
	private String inputText;
	private String errorMessages;
	
	// Constructors :
	
	public PCSFCConsoleParser(final RevisorConsolePCSFC console, final String inputText) {
		super();
		this.console = console;
		this.inputText = inputText;
	}
	
	public PCSFCConsoleParser(final RevisorConsolePCSFC console, final String inputText, final Scanner scanner) {
		super(scanner);
		this.console = console;
		this.inputText = inputText;
	}
	
	public PCSFCConsoleParser(final RevisorConsolePCSFC console, final String inputText, final Scanner scanner, final SymbolFactory factory) {
		super(scanner, factory);
		this.console = console;
		this.inputText = inputText;
	}
	
	// Getters :
	
	public RevisorConsolePCSFC getConsole() {
		return this.console;
	}
	
	public String getInputText() {
		return this.inputText;
	}
	
	public String getErrorMessage() {
		return this.errorMessages;
	}
	
	// Methods :
	
	private void addErrorMessage(String message) {
		if(this.errorMessages == null || this.errorMessages.isEmpty()) {
			this.errorMessages = message;
		}
		else {
			this.errorMessages += "\n" + message;
		}
	}
	
	@Override
	public void report_error(String message, Object info) {
		StringBuffer buffer = new StringBuffer("Parsing Error");
		
		if(info instanceof Symbol) {
			Symbol s = (Symbol) info;
			
			if(s.left >= 0) {
				buffer.append(" at line " + (s.left + 1));
				
				if(s.right >= 0) {
					buffer.append(", column " + (s.right + 1));
				}
			}
		}
		
		buffer.append(" : " + message);
		this.addErrorMessage(buffer.toString());
	}
	
	@Override
	public void report_fatal_error(String message, Object info) throws ParserException {
		this.done_parsing();
		this.report_error(message, info);
		throw new ParserException(this.errorMessages, null, true, false);
	}
	


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$PCSFCConsoleParser$actions {
  private final PCSFCConsoleParser parser;

  /** Constructor */
  CUP$PCSFCConsoleParser$actions(PCSFCConsoleParser parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$PCSFCConsoleParser$do_action_part00000000(
    int                        CUP$PCSFCConsoleParser$act_num,
    java_cup.runtime.lr_parser CUP$PCSFCConsoleParser$parser,
    java.util.Stack            CUP$PCSFCConsoleParser$stack,
    int                        CUP$PCSFCConsoleParser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$PCSFCConsoleParser$result;

      /* select the action based on the action number */
      switch (CUP$PCSFCConsoleParser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= INSTRUCTION EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.elementAt(CUP$PCSFCConsoleParser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.elementAt(CUP$PCSFCConsoleParser$top-1)).right;
		Instruction<RevisorConsolePCSFC> start_val = (Instruction<RevisorConsolePCSFC>)((java_cup.runtime.Symbol) CUP$PCSFCConsoleParser$stack.elementAt(CUP$PCSFCConsoleParser$top-1)).value;
		RESULT = start_val;
              CUP$PCSFCConsoleParser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.elementAt(CUP$PCSFCConsoleParser$top-1)), ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$PCSFCConsoleParser$parser.done_parsing();
          return CUP$PCSFCConsoleParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // INSTRUCTION ::= RAW_INSTRUCTION END_OF_INSTRUCTION 
            {
              Instruction<RevisorConsolePCSFC> RESULT =null;
		int raw_insleft = ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.elementAt(CUP$PCSFCConsoleParser$top-1)).left;
		int raw_insright = ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.elementAt(CUP$PCSFCConsoleParser$top-1)).right;
		Instruction<RevisorConsolePCSFC> raw_ins = (Instruction<RevisorConsolePCSFC>)((java_cup.runtime.Symbol) CUP$PCSFCConsoleParser$stack.elementAt(CUP$PCSFCConsoleParser$top-1)).value;
		
									RESULT = raw_ins;
								
              CUP$PCSFCConsoleParser$result = parser.getSymbolFactory().newSymbol("INSTRUCTION",0, ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.elementAt(CUP$PCSFCConsoleParser$top-1)), ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.peek()), RESULT);
            }
          return CUP$PCSFCConsoleParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // INSTRUCTION ::= LOAD_INS 
            {
              Instruction<RevisorConsolePCSFC> RESULT =null;
		int load_insleft = ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.peek()).left;
		int load_insright = ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.peek()).right;
		Instruction<RevisorConsolePCSFC> load_ins = (Instruction<RevisorConsolePCSFC>)((java_cup.runtime.Symbol) CUP$PCSFCConsoleParser$stack.peek()).value;
		
									RESULT = load_ins;
								
              CUP$PCSFCConsoleParser$result = parser.getSymbolFactory().newSymbol("INSTRUCTION",0, ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.peek()), RESULT);
            }
          return CUP$PCSFCConsoleParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // INSTRUCTION ::= CLEAR_INS 
            {
              Instruction<RevisorConsolePCSFC> RESULT =null;
		int clear_insleft = ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.peek()).left;
		int clear_insright = ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.peek()).right;
		Instruction<RevisorConsolePCSFC> clear_ins = (Instruction<RevisorConsolePCSFC>)((java_cup.runtime.Symbol) CUP$PCSFCConsoleParser$stack.peek()).value;
		
									RESULT = clear_ins;
								
              CUP$PCSFCConsoleParser$result = parser.getSymbolFactory().newSymbol("INSTRUCTION",0, ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.peek()), RESULT);
            }
          return CUP$PCSFCConsoleParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // INSTRUCTION ::= PRINTVARS_INS 
            {
              Instruction<RevisorConsolePCSFC> RESULT =null;
		int printvrs_insleft = ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.peek()).left;
		int printvrs_insright = ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.peek()).right;
		Instruction<RevisorConsolePCSFC> printvrs_ins = (Instruction<RevisorConsolePCSFC>)((java_cup.runtime.Symbol) CUP$PCSFCConsoleParser$stack.peek()).value;
		
									RESULT = printvrs_ins;
								
              CUP$PCSFCConsoleParser$result = parser.getSymbolFactory().newSymbol("INSTRUCTION",0, ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.peek()), RESULT);
            }
          return CUP$PCSFCConsoleParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // INSTRUCTION ::= PRINTIDF_INS 
            {
              Instruction<RevisorConsolePCSFC> RESULT =null;
		int pridf_insleft = ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.peek()).left;
		int pridf_insright = ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.peek()).right;
		Instruction<RevisorConsolePCSFC> pridf_ins = (Instruction<RevisorConsolePCSFC>)((java_cup.runtime.Symbol) CUP$PCSFCConsoleParser$stack.peek()).value;
		
									RESULT = pridf_ins;
								
              CUP$PCSFCConsoleParser$result = parser.getSymbolFactory().newSymbol("INSTRUCTION",0, ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.peek()), RESULT);
            }
          return CUP$PCSFCConsoleParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // RAW_INSTRUCTION ::= DECLARATION 
            {
              Instruction<RevisorConsolePCSFC> RESULT =null;
		int declleft = ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.peek()).left;
		int declright = ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.peek()).right;
		Instruction<RevisorConsolePCSFC> decl = (Instruction<RevisorConsolePCSFC>)((java_cup.runtime.Symbol) CUP$PCSFCConsoleParser$stack.peek()).value;
		
									RESULT = decl; 
								
              CUP$PCSFCConsoleParser$result = parser.getSymbolFactory().newSymbol("RAW_INSTRUCTION",1, ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.peek()), RESULT);
            }
          return CUP$PCSFCConsoleParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // RAW_INSTRUCTION ::= ASSIGNMENT 
            {
              Instruction<RevisorConsolePCSFC> RESULT =null;
		int assleft = ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.peek()).left;
		int assright = ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.peek()).right;
		Instruction<RevisorConsolePCSFC> ass = (Instruction<RevisorConsolePCSFC>)((java_cup.runtime.Symbol) CUP$PCSFCConsoleParser$stack.peek()).value;
		
									RESULT = ass; 
								
              CUP$PCSFCConsoleParser$result = parser.getSymbolFactory().newSymbol("RAW_INSTRUCTION",1, ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.peek()), RESULT);
            }
          return CUP$PCSFCConsoleParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // RAW_INSTRUCTION ::= LOAD_INS 
            {
              Instruction<RevisorConsolePCSFC> RESULT =null;
		int load_insleft = ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.peek()).left;
		int load_insright = ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.peek()).right;
		Instruction<RevisorConsolePCSFC> load_ins = (Instruction<RevisorConsolePCSFC>)((java_cup.runtime.Symbol) CUP$PCSFCConsoleParser$stack.peek()).value;
		
									RESULT = load_ins;
								
              CUP$PCSFCConsoleParser$result = parser.getSymbolFactory().newSymbol("RAW_INSTRUCTION",1, ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.peek()), RESULT);
            }
          return CUP$PCSFCConsoleParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // RAW_INSTRUCTION ::= CLEAR_INS 
            {
              Instruction<RevisorConsolePCSFC> RESULT =null;
		int clear_insleft = ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.peek()).left;
		int clear_insright = ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.peek()).right;
		Instruction<RevisorConsolePCSFC> clear_ins = (Instruction<RevisorConsolePCSFC>)((java_cup.runtime.Symbol) CUP$PCSFCConsoleParser$stack.peek()).value;
		
									RESULT = clear_ins;
								
              CUP$PCSFCConsoleParser$result = parser.getSymbolFactory().newSymbol("RAW_INSTRUCTION",1, ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.peek()), RESULT);
            }
          return CUP$PCSFCConsoleParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // RAW_INSTRUCTION ::= PRINTVARS_INS 
            {
              Instruction<RevisorConsolePCSFC> RESULT =null;
		int printvrs_insleft = ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.peek()).left;
		int printvrs_insright = ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.peek()).right;
		Instruction<RevisorConsolePCSFC> printvrs_ins = (Instruction<RevisorConsolePCSFC>)((java_cup.runtime.Symbol) CUP$PCSFCConsoleParser$stack.peek()).value;
		
									RESULT = printvrs_ins;
								
              CUP$PCSFCConsoleParser$result = parser.getSymbolFactory().newSymbol("RAW_INSTRUCTION",1, ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.peek()), RESULT);
            }
          return CUP$PCSFCConsoleParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // RAW_INSTRUCTION ::= PRINTIDF_INS 
            {
              Instruction<RevisorConsolePCSFC> RESULT =null;
		int pridf_insleft = ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.peek()).left;
		int pridf_insright = ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.peek()).right;
		Instruction<RevisorConsolePCSFC> pridf_ins = (Instruction<RevisorConsolePCSFC>)((java_cup.runtime.Symbol) CUP$PCSFCConsoleParser$stack.peek()).value;
		
									RESULT = pridf_ins;
								
              CUP$PCSFCConsoleParser$result = parser.getSymbolFactory().newSymbol("RAW_INSTRUCTION",1, ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.peek()), RESULT);
            }
          return CUP$PCSFCConsoleParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // LOAD_INS ::= LOAD FILE 
            {
              Instruction<RevisorConsolePCSFC> RESULT =null;
		int fileleft = ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.peek()).left;
		int fileright = ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.peek()).right;
		String file = (String)((java_cup.runtime.Symbol) CUP$PCSFCConsoleParser$stack.peek()).value;
		
									RESULT = new PCSFC_Load<>(this.parser.getConsole(), this.parser.getInputText(), file);
								
              CUP$PCSFCConsoleParser$result = parser.getSymbolFactory().newSymbol("LOAD_INS",10, ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.elementAt(CUP$PCSFCConsoleParser$top-1)), ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.peek()), RESULT);
            }
          return CUP$PCSFCConsoleParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // CLEAR_INS ::= CLEAR 
            {
              Instruction<RevisorConsolePCSFC> RESULT =null;
		
									RESULT = new PCSFC_Clear<>(this.parser.getConsole(), this.parser.getInputText());
								
              CUP$PCSFCConsoleParser$result = parser.getSymbolFactory().newSymbol("CLEAR_INS",11, ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.peek()), RESULT);
            }
          return CUP$PCSFCConsoleParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // PRINTVARS_INS ::= PRINTVARS 
            {
              Instruction<RevisorConsolePCSFC> RESULT =null;
		
									RESULT = new PCSFC_PrintVars<>(this.parser.getConsole(), this.parser.getInputText());
								
              CUP$PCSFCConsoleParser$result = parser.getSymbolFactory().newSymbol("PRINTVARS_INS",12, ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.peek()), RESULT);
            }
          return CUP$PCSFCConsoleParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // PRINTIDF_INS ::= IDENTIFIER 
            {
              Instruction<RevisorConsolePCSFC> RESULT =null;
		int idfleft = ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.peek()).left;
		int idfright = ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.peek()).right;
		String idf = (String)((java_cup.runtime.Symbol) CUP$PCSFCConsoleParser$stack.peek()).value;
		
									RESULT = new PCSFC_PrintIdf<>(this.parser.getConsole(), this.parser.getInputText(), idf);
								
              CUP$PCSFCConsoleParser$result = parser.getSymbolFactory().newSymbol("PRINTIDF_INS",13, ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.peek()), RESULT);
            }
          return CUP$PCSFCConsoleParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // DECLARATION ::= DECLARE_INTEGER 
            {
              Instruction<RevisorConsolePCSFC> RESULT =null;
		int decl_intleft = ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.peek()).left;
		int decl_intright = ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.peek()).right;
		Instruction<RevisorConsolePCSFC> decl_int = (Instruction<RevisorConsolePCSFC>)((java_cup.runtime.Symbol) CUP$PCSFCConsoleParser$stack.peek()).value;
		
									RESULT = decl_int; 
								
              CUP$PCSFCConsoleParser$result = parser.getSymbolFactory().newSymbol("DECLARATION",2, ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.peek()), RESULT);
            }
          return CUP$PCSFCConsoleParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // DECLARATION ::= DECLARE_REAL 
            {
              Instruction<RevisorConsolePCSFC> RESULT =null;
		int decl_releft = ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.peek()).left;
		int decl_reright = ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.peek()).right;
		Instruction<RevisorConsolePCSFC> decl_re = (Instruction<RevisorConsolePCSFC>)((java_cup.runtime.Symbol) CUP$PCSFCConsoleParser$stack.peek()).value;
		
									RESULT = decl_re; 
								
              CUP$PCSFCConsoleParser$result = parser.getSymbolFactory().newSymbol("DECLARATION",2, ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.peek()), RESULT);
            }
          return CUP$PCSFCConsoleParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // DECLARATION ::= DECLARE_FORMULA 
            {
              Instruction<RevisorConsolePCSFC> RESULT =null;
		int decl_formleft = ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.peek()).left;
		int decl_formright = ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.peek()).right;
		Instruction<RevisorConsolePCSFC> decl_form = (Instruction<RevisorConsolePCSFC>)((java_cup.runtime.Symbol) CUP$PCSFCConsoleParser$stack.peek()).value;
		
									RESULT = decl_form; 
								
              CUP$PCSFCConsoleParser$result = parser.getSymbolFactory().newSymbol("DECLARATION",2, ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.peek()), RESULT);
            }
          return CUP$PCSFCConsoleParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // DECLARATION ::= DECLARE_CONSTANT 
            {
              Instruction<RevisorConsolePCSFC> RESULT =null;
		int decl_constleft = ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.peek()).left;
		int decl_constright = ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.peek()).right;
		Instruction<RevisorConsolePCSFC> decl_const = (Instruction<RevisorConsolePCSFC>)((java_cup.runtime.Symbol) CUP$PCSFCConsoleParser$stack.peek()).value;
		
									RESULT = decl_const; 
								
              CUP$PCSFCConsoleParser$result = parser.getSymbolFactory().newSymbol("DECLARATION",2, ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.peek()), RESULT);
            }
          return CUP$PCSFCConsoleParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // DECLARATION ::= DECLARE_BOOLEAN 
            {
              Instruction<RevisorConsolePCSFC> RESULT =null;
		int decl_boolleft = ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.peek()).left;
		int decl_boolright = ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.peek()).right;
		Instruction<RevisorConsolePCSFC> decl_bool = (Instruction<RevisorConsolePCSFC>)((java_cup.runtime.Symbol) CUP$PCSFCConsoleParser$stack.peek()).value;
		
									RESULT = decl_bool; 
								
              CUP$PCSFCConsoleParser$result = parser.getSymbolFactory().newSymbol("DECLARATION",2, ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.peek()), RESULT);
            }
          return CUP$PCSFCConsoleParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // DECLARATION ::= DECLARE_ENUM 
            {
              Instruction<RevisorConsolePCSFC> RESULT =null;
		int decl_enumleft = ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.peek()).left;
		int decl_enumright = ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.peek()).right;
		Instruction<RevisorConsolePCSFC> decl_enum = (Instruction<RevisorConsolePCSFC>)((java_cup.runtime.Symbol) CUP$PCSFCConsoleParser$stack.peek()).value;
		
									RESULT = decl_enum; 
								
              CUP$PCSFCConsoleParser$result = parser.getSymbolFactory().newSymbol("DECLARATION",2, ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.peek()), RESULT);
            }
          return CUP$PCSFCConsoleParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // DECLARE_INTEGER ::= IDENTIFIER_LIST COLON INTEGER_DECLARATION_KEYWORD 
            {
              Instruction<RevisorConsolePCSFC> RESULT =null;
		int alidfleft = ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.elementAt(CUP$PCSFCConsoleParser$top-2)).left;
		int alidfright = ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.elementAt(CUP$PCSFCConsoleParser$top-2)).right;
		ArrayList<String> alidf = (ArrayList<String>)((java_cup.runtime.Symbol) CUP$PCSFCConsoleParser$stack.elementAt(CUP$PCSFCConsoleParser$top-2)).value;
		
									RESULT = new PCSFC_DeclarationInteger<RevisorConsolePCSFC>(this.parser.getConsole(), this.parser.getInputText(), alidf);
								
              CUP$PCSFCConsoleParser$result = parser.getSymbolFactory().newSymbol("DECLARE_INTEGER",3, ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.elementAt(CUP$PCSFCConsoleParser$top-2)), ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.peek()), RESULT);
            }
          return CUP$PCSFCConsoleParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // DECLARE_REAL ::= IDENTIFIER_LIST COLON REAL_DECLARATION_KEYWORD 
            {
              Instruction<RevisorConsolePCSFC> RESULT =null;
		int alidfleft = ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.elementAt(CUP$PCSFCConsoleParser$top-2)).left;
		int alidfright = ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.elementAt(CUP$PCSFCConsoleParser$top-2)).right;
		ArrayList<String> alidf = (ArrayList<String>)((java_cup.runtime.Symbol) CUP$PCSFCConsoleParser$stack.elementAt(CUP$PCSFCConsoleParser$top-2)).value;
		
									RESULT = new PCSFC_DeclarationReal<RevisorConsolePCSFC>(this.parser.getConsole(), this.parser.getInputText(), alidf);
								
              CUP$PCSFCConsoleParser$result = parser.getSymbolFactory().newSymbol("DECLARE_REAL",4, ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.elementAt(CUP$PCSFCConsoleParser$top-2)), ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.peek()), RESULT);
            }
          return CUP$PCSFCConsoleParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // DECLARE_FORMULA ::= IDENTIFIER_LIST COLON FORMULA_DECLARATION_KEYWORD 
            {
              Instruction<RevisorConsolePCSFC> RESULT =null;
		int alidfleft = ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.elementAt(CUP$PCSFCConsoleParser$top-2)).left;
		int alidfright = ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.elementAt(CUP$PCSFCConsoleParser$top-2)).right;
		ArrayList<String> alidf = (ArrayList<String>)((java_cup.runtime.Symbol) CUP$PCSFCConsoleParser$stack.elementAt(CUP$PCSFCConsoleParser$top-2)).value;
		
									RESULT = new PCSFC_DeclarationFormula<RevisorConsolePCSFC>(this.parser.getConsole(), this.parser.getInputText(), alidf);
								
              CUP$PCSFCConsoleParser$result = parser.getSymbolFactory().newSymbol("DECLARE_FORMULA",5, ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.elementAt(CUP$PCSFCConsoleParser$top-2)), ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.peek()), RESULT);
            }
          return CUP$PCSFCConsoleParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // DECLARE_CONSTANT ::= CONST_DECLARATION_KEYWORD IDENTIFIER SIMPLE_EQUAL REAL 
            {
              Instruction<RevisorConsolePCSFC> RESULT =null;
		int idfleft = ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.elementAt(CUP$PCSFCConsoleParser$top-2)).left;
		int idfright = ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.elementAt(CUP$PCSFCConsoleParser$top-2)).right;
		String idf = (String)((java_cup.runtime.Symbol) CUP$PCSFCConsoleParser$stack.elementAt(CUP$PCSFCConsoleParser$top-2)).value;
		int realleft = ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.peek()).left;
		int realright = ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.peek()).right;
		String real = (String)((java_cup.runtime.Symbol) CUP$PCSFCConsoleParser$stack.peek()).value;
		
									RESULT = new PCSFC_DeclarationConstant<RevisorConsolePCSFC>(this.parser.getConsole(), this.parser.getInputText(), idf, real);
								
              CUP$PCSFCConsoleParser$result = parser.getSymbolFactory().newSymbol("DECLARE_CONSTANT",6, ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.elementAt(CUP$PCSFCConsoleParser$top-3)), ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.peek()), RESULT);
            }
          return CUP$PCSFCConsoleParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // DECLARE_BOOLEAN ::= IDENTIFIER_LIST COLON BOOLEAN_DECLARATION_KEYWORD 
            {
              Instruction<RevisorConsolePCSFC> RESULT =null;
		int alidfleft = ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.elementAt(CUP$PCSFCConsoleParser$top-2)).left;
		int alidfright = ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.elementAt(CUP$PCSFCConsoleParser$top-2)).right;
		ArrayList<String> alidf = (ArrayList<String>)((java_cup.runtime.Symbol) CUP$PCSFCConsoleParser$stack.elementAt(CUP$PCSFCConsoleParser$top-2)).value;
		
									RESULT = new PCSFC_DeclarationBoolean<RevisorConsolePCSFC>(this.parser.getConsole(), this.parser.getInputText(), alidf);
								
              CUP$PCSFCConsoleParser$result = parser.getSymbolFactory().newSymbol("DECLARE_BOOLEAN",8, ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.elementAt(CUP$PCSFCConsoleParser$top-2)), ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.peek()), RESULT);
            }
          return CUP$PCSFCConsoleParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // DECLARE_ENUM ::= ENUM_DECLARATION_KEYWORD IDENTIFIER OPENING_PARENTHESIS MODALITY_LIST CLOSING_PARENTHESIS 
            {
              Instruction<RevisorConsolePCSFC> RESULT =null;
		int idfleft = ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.elementAt(CUP$PCSFCConsoleParser$top-3)).left;
		int idfright = ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.elementAt(CUP$PCSFCConsoleParser$top-3)).right;
		String idf = (String)((java_cup.runtime.Symbol) CUP$PCSFCConsoleParser$stack.elementAt(CUP$PCSFCConsoleParser$top-3)).value;
		int almodleft = ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.elementAt(CUP$PCSFCConsoleParser$top-1)).left;
		int almodright = ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.elementAt(CUP$PCSFCConsoleParser$top-1)).right;
		ArrayList<String> almod = (ArrayList<String>)((java_cup.runtime.Symbol) CUP$PCSFCConsoleParser$stack.elementAt(CUP$PCSFCConsoleParser$top-1)).value;
		
									RESULT = new PCSFC_DeclarationEnum<RevisorConsolePCSFC>(this.parser.getConsole(), this.parser.getInputText(), idf, almod);
								
              CUP$PCSFCConsoleParser$result = parser.getSymbolFactory().newSymbol("DECLARE_ENUM",9, ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.elementAt(CUP$PCSFCConsoleParser$top-4)), ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.peek()), RESULT);
            }
          return CUP$PCSFCConsoleParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // MODALITY_LIST ::= MODALITY_LIST COMMA MODALITY 
            {
              ArrayList<String> RESULT =null;
		int almodleft = ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.elementAt(CUP$PCSFCConsoleParser$top-2)).left;
		int almodright = ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.elementAt(CUP$PCSFCConsoleParser$top-2)).right;
		ArrayList<String> almod = (ArrayList<String>)((java_cup.runtime.Symbol) CUP$PCSFCConsoleParser$stack.elementAt(CUP$PCSFCConsoleParser$top-2)).value;
		int modleft = ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.peek()).left;
		int modright = ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.peek()).right;
		String mod = (String)((java_cup.runtime.Symbol) CUP$PCSFCConsoleParser$stack.peek()).value;
		
									almod.add(mod);
									RESULT = almod;
								
              CUP$PCSFCConsoleParser$result = parser.getSymbolFactory().newSymbol("MODALITY_LIST",15, ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.elementAt(CUP$PCSFCConsoleParser$top-2)), ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.peek()), RESULT);
            }
          return CUP$PCSFCConsoleParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // MODALITY_LIST ::= MODALITY 
            {
              ArrayList<String> RESULT =null;
		int modleft = ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.peek()).left;
		int modright = ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.peek()).right;
		String mod = (String)((java_cup.runtime.Symbol) CUP$PCSFCConsoleParser$stack.peek()).value;
		
									ArrayList<String> almod = new ArrayList<>();
									almod.add(mod);
									RESULT = almod;
								
              CUP$PCSFCConsoleParser$result = parser.getSymbolFactory().newSymbol("MODALITY_LIST",15, ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.peek()), RESULT);
            }
          return CUP$PCSFCConsoleParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // IDENTIFIER_LIST ::= IDENTIFIER_LIST COMMA IDENTIFIER 
            {
              ArrayList<String> RESULT =null;
		int alidfleft = ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.elementAt(CUP$PCSFCConsoleParser$top-2)).left;
		int alidfright = ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.elementAt(CUP$PCSFCConsoleParser$top-2)).right;
		ArrayList<String> alidf = (ArrayList<String>)((java_cup.runtime.Symbol) CUP$PCSFCConsoleParser$stack.elementAt(CUP$PCSFCConsoleParser$top-2)).value;
		int idfleft = ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.peek()).left;
		int idfright = ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.peek()).right;
		String idf = (String)((java_cup.runtime.Symbol) CUP$PCSFCConsoleParser$stack.peek()).value;
		
									alidf.add(idf);
									RESULT = alidf;
								
              CUP$PCSFCConsoleParser$result = parser.getSymbolFactory().newSymbol("IDENTIFIER_LIST",14, ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.elementAt(CUP$PCSFCConsoleParser$top-2)), ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.peek()), RESULT);
            }
          return CUP$PCSFCConsoleParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // IDENTIFIER_LIST ::= IDENTIFIER 
            {
              ArrayList<String> RESULT =null;
		int idfleft = ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.peek()).left;
		int idfright = ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.peek()).right;
		String idf = (String)((java_cup.runtime.Symbol) CUP$PCSFCConsoleParser$stack.peek()).value;
		
									ArrayList<String> alidf = new ArrayList<>();
									alidf.add(idf);
									RESULT = alidf;
								
              CUP$PCSFCConsoleParser$result = parser.getSymbolFactory().newSymbol("IDENTIFIER_LIST",14, ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.peek()), RESULT);
            }
          return CUP$PCSFCConsoleParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // ASSIGNMENT ::= IDENTIFIER ASSIGNMENT_OPERATOR FORMULA 
            {
              Instruction<RevisorConsolePCSFC> RESULT =null;
		int idfleft = ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.elementAt(CUP$PCSFCConsoleParser$top-2)).left;
		int idfright = ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.elementAt(CUP$PCSFCConsoleParser$top-2)).right;
		String idf = (String)((java_cup.runtime.Symbol) CUP$PCSFCConsoleParser$stack.elementAt(CUP$PCSFCConsoleParser$top-2)).value;
		int formleft = ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.peek()).left;
		int formright = ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.peek()).right;
		Formula<RevisorConsolePCSFC,PCSFCFormula> form = (Formula<RevisorConsolePCSFC,PCSFCFormula>)((java_cup.runtime.Symbol) CUP$PCSFCConsoleParser$stack.peek()).value;
		
									RESULT = new PCSFC_Assignment<RevisorConsolePCSFC>(this.parser.getConsole(), this.parser.getInputText(), new PCSFC_Identifier<RevisorConsolePCSFC>(idf), form); 
								
              CUP$PCSFCConsoleParser$result = parser.getSymbolFactory().newSymbol("ASSIGNMENT",7, ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.elementAt(CUP$PCSFCConsoleParser$top-2)), ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.peek()), RESULT);
            }
          return CUP$PCSFCConsoleParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // FORMULA ::= REVISE_FORMULA 
            {
              Formula<RevisorConsolePCSFC,PCSFCFormula> RESULT =null;
		int rev_formleft = ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.peek()).left;
		int rev_formright = ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.peek()).right;
		Formula<RevisorConsolePCSFC,PCSFCFormula> rev_form = (Formula<RevisorConsolePCSFC,PCSFCFormula>)((java_cup.runtime.Symbol) CUP$PCSFCConsoleParser$stack.peek()).value;
		
									RESULT = rev_form;
								
              CUP$PCSFCConsoleParser$result = parser.getSymbolFactory().newSymbol("FORMULA",16, ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.peek()), RESULT);
            }
          return CUP$PCSFCConsoleParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // FORMULA ::= BINARY_FORMULA 
            {
              Formula<RevisorConsolePCSFC,PCSFCFormula> RESULT =null;
		int bin_formleft = ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.peek()).left;
		int bin_formright = ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.peek()).right;
		Formula<RevisorConsolePCSFC,PCSFCFormula> bin_form = (Formula<RevisorConsolePCSFC,PCSFCFormula>)((java_cup.runtime.Symbol) CUP$PCSFCConsoleParser$stack.peek()).value;
		
									RESULT = bin_form;
								
              CUP$PCSFCConsoleParser$result = parser.getSymbolFactory().newSymbol("FORMULA",16, ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.peek()), RESULT);
            }
          return CUP$PCSFCConsoleParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // REVISE_FORMULA ::= REVISE_KEYWORD OPENING_PARENTHESIS IDENTIFIER COMMA IDENTIFIER COMMA IDENTIFIER CLOSING_PARENTHESIS 
            {
              Formula<RevisorConsolePCSFC,PCSFCFormula> RESULT =null;
		int idf1left = ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.elementAt(CUP$PCSFCConsoleParser$top-5)).left;
		int idf1right = ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.elementAt(CUP$PCSFCConsoleParser$top-5)).right;
		String idf1 = (String)((java_cup.runtime.Symbol) CUP$PCSFCConsoleParser$stack.elementAt(CUP$PCSFCConsoleParser$top-5)).value;
		int idf2left = ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.elementAt(CUP$PCSFCConsoleParser$top-3)).left;
		int idf2right = ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.elementAt(CUP$PCSFCConsoleParser$top-3)).right;
		String idf2 = (String)((java_cup.runtime.Symbol) CUP$PCSFCConsoleParser$stack.elementAt(CUP$PCSFCConsoleParser$top-3)).value;
		int idf3left = ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.elementAt(CUP$PCSFCConsoleParser$top-1)).left;
		int idf3right = ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.elementAt(CUP$PCSFCConsoleParser$top-1)).right;
		String idf3 = (String)((java_cup.runtime.Symbol) CUP$PCSFCConsoleParser$stack.elementAt(CUP$PCSFCConsoleParser$top-1)).value;
		
									RESULT = new PCSFC_Revise(idf1, idf2, idf3);
								
              CUP$PCSFCConsoleParser$result = parser.getSymbolFactory().newSymbol("REVISE_FORMULA",17, ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.elementAt(CUP$PCSFCConsoleParser$top-7)), ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.peek()), RESULT);
            }
          return CUP$PCSFCConsoleParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // REVISE_FORMULA ::= REVISE_KEYWORD OPENING_PARENTHESIS IDENTIFIER COMMA IDENTIFIER COMMA REAL CLOSING_PARENTHESIS 
            {
              Formula<RevisorConsolePCSFC,PCSFCFormula> RESULT =null;
		int idf1left = ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.elementAt(CUP$PCSFCConsoleParser$top-5)).left;
		int idf1right = ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.elementAt(CUP$PCSFCConsoleParser$top-5)).right;
		String idf1 = (String)((java_cup.runtime.Symbol) CUP$PCSFCConsoleParser$stack.elementAt(CUP$PCSFCConsoleParser$top-5)).value;
		int idf2left = ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.elementAt(CUP$PCSFCConsoleParser$top-3)).left;
		int idf2right = ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.elementAt(CUP$PCSFCConsoleParser$top-3)).right;
		String idf2 = (String)((java_cup.runtime.Symbol) CUP$PCSFCConsoleParser$stack.elementAt(CUP$PCSFCConsoleParser$top-3)).value;
		int realleft = ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.elementAt(CUP$PCSFCConsoleParser$top-1)).left;
		int realright = ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.elementAt(CUP$PCSFCConsoleParser$top-1)).right;
		String real = (String)((java_cup.runtime.Symbol) CUP$PCSFCConsoleParser$stack.elementAt(CUP$PCSFCConsoleParser$top-1)).value;
		
									boolean isDouble = true;
									double realP = 0.0;
        							try {
            							realP = Double.parseDouble(real);
        							} catch (NumberFormatException e) {
           								 isDouble = false;
        							}
        							if (isDouble) {
            							RESULT = new PCSFC_Revise(idf1, idf2, realP);
            						}
        							else {
            							RESULT = new PCSFC_Revise(idf1, idf2, real);
            						}
								
              CUP$PCSFCConsoleParser$result = parser.getSymbolFactory().newSymbol("REVISE_FORMULA",17, ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.elementAt(CUP$PCSFCConsoleParser$top-7)), ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.peek()), RESULT);
            }
          return CUP$PCSFCConsoleParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // BINARY_FORMULA ::= OPENING_PARENTHESIS BINARY_FORMULA CLOSING_PARENTHESIS 
            {
              Formula<RevisorConsolePCSFC,PCSFCFormula> RESULT =null;
		int bin_formleft = ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.elementAt(CUP$PCSFCConsoleParser$top-1)).left;
		int bin_formright = ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.elementAt(CUP$PCSFCConsoleParser$top-1)).right;
		Formula<RevisorConsolePCSFC,PCSFCFormula> bin_form = (Formula<RevisorConsolePCSFC,PCSFCFormula>)((java_cup.runtime.Symbol) CUP$PCSFCConsoleParser$stack.elementAt(CUP$PCSFCConsoleParser$top-1)).value;
		
									RESULT = bin_form;
								
              CUP$PCSFCConsoleParser$result = parser.getSymbolFactory().newSymbol("BINARY_FORMULA",18, ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.elementAt(CUP$PCSFCConsoleParser$top-2)), ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.peek()), RESULT);
            }
          return CUP$PCSFCConsoleParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // BINARY_FORMULA ::= NEGATIVE_FORMULA_SYMBOL BINARY_FORMULA 
            {
              Formula<RevisorConsolePCSFC,PCSFCFormula> RESULT =null;
		int bin_formleft = ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.peek()).left;
		int bin_formright = ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.peek()).right;
		Formula<RevisorConsolePCSFC,PCSFCFormula> bin_form = (Formula<RevisorConsolePCSFC,PCSFCFormula>)((java_cup.runtime.Symbol) CUP$PCSFCConsoleParser$stack.peek()).value;
		
									RESULT = new PCSFC_Not<RevisorConsolePCSFC>(bin_form);
								
              CUP$PCSFCConsoleParser$result = parser.getSymbolFactory().newSymbol("BINARY_FORMULA",18, ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.elementAt(CUP$PCSFCConsoleParser$top-1)), ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.peek()), RESULT);
            }
          return CUP$PCSFCConsoleParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // BINARY_FORMULA ::= BINARY_FORMULA BINARY_FORMULA_OPERATOR UNARY_FORMULA 
            {
              Formula<RevisorConsolePCSFC,PCSFCFormula> RESULT =null;
		int bin_formleft = ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.elementAt(CUP$PCSFCConsoleParser$top-2)).left;
		int bin_formright = ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.elementAt(CUP$PCSFCConsoleParser$top-2)).right;
		Formula<RevisorConsolePCSFC,PCSFCFormula> bin_form = (Formula<RevisorConsolePCSFC,PCSFCFormula>)((java_cup.runtime.Symbol) CUP$PCSFCConsoleParser$stack.elementAt(CUP$PCSFCConsoleParser$top-2)).value;
		int opleft = ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.elementAt(CUP$PCSFCConsoleParser$top-1)).left;
		int opright = ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.elementAt(CUP$PCSFCConsoleParser$top-1)).right;
		String op = (String)((java_cup.runtime.Symbol) CUP$PCSFCConsoleParser$stack.elementAt(CUP$PCSFCConsoleParser$top-1)).value;
		int un_formleft = ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.peek()).left;
		int un_formright = ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.peek()).right;
		Formula<RevisorConsolePCSFC,PCSFCFormula> un_form = (Formula<RevisorConsolePCSFC,PCSFCFormula>)((java_cup.runtime.Symbol) CUP$PCSFCConsoleParser$stack.peek()).value;
		
									Formula<RevisorConsolePCSFC, PCSFCFormula> formula;
									switch (op) {
										case "&":
											formula = new PCSFC_And(bin_form, un_form);
											break;
										case "|":
											formula = new PCSFC_Or(bin_form, un_form);
											break;
										case "=>":
											formula = new PCSFC_Impl(bin_form, un_form);
											break;
										case "<=>":
											formula = new PCSFC_Equiv(bin_form, un_form);
											break;
										case "^":
											formula = new PCSFC_Xor(bin_form, un_form);
											break;
										default:
											formula = new PCSFC_And(bin_form, un_form);
									}
									RESULT = formula;
								
              CUP$PCSFCConsoleParser$result = parser.getSymbolFactory().newSymbol("BINARY_FORMULA",18, ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.elementAt(CUP$PCSFCConsoleParser$top-2)), ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.peek()), RESULT);
            }
          return CUP$PCSFCConsoleParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // BINARY_FORMULA ::= BINARY_FORMULA BINARY_FORMULA_OPERATOR OPENING_PARENTHESIS BINARY_FORMULA CLOSING_PARENTHESIS 
            {
              Formula<RevisorConsolePCSFC,PCSFCFormula> RESULT =null;
		int bin_form_leftleft = ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.elementAt(CUP$PCSFCConsoleParser$top-4)).left;
		int bin_form_leftright = ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.elementAt(CUP$PCSFCConsoleParser$top-4)).right;
		Formula<RevisorConsolePCSFC,PCSFCFormula> bin_form_left = (Formula<RevisorConsolePCSFC,PCSFCFormula>)((java_cup.runtime.Symbol) CUP$PCSFCConsoleParser$stack.elementAt(CUP$PCSFCConsoleParser$top-4)).value;
		int opleft = ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.elementAt(CUP$PCSFCConsoleParser$top-3)).left;
		int opright = ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.elementAt(CUP$PCSFCConsoleParser$top-3)).right;
		String op = (String)((java_cup.runtime.Symbol) CUP$PCSFCConsoleParser$stack.elementAt(CUP$PCSFCConsoleParser$top-3)).value;
		int bin_form_rightleft = ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.elementAt(CUP$PCSFCConsoleParser$top-1)).left;
		int bin_form_rightright = ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.elementAt(CUP$PCSFCConsoleParser$top-1)).right;
		Formula<RevisorConsolePCSFC,PCSFCFormula> bin_form_right = (Formula<RevisorConsolePCSFC,PCSFCFormula>)((java_cup.runtime.Symbol) CUP$PCSFCConsoleParser$stack.elementAt(CUP$PCSFCConsoleParser$top-1)).value;
		
									Formula<RevisorConsolePCSFC, PCSFCFormula> formula;
									switch (op) {
										case "&":
											formula = new PCSFC_And(bin_form_left, bin_form_right);
											break;
										case "|":
											formula = new PCSFC_Or(bin_form_left, bin_form_right);
											break;
										case "=>":
											formula = new PCSFC_Impl(bin_form_left, bin_form_right);
											break;
										case "<=>":
											formula = new PCSFC_Equiv(bin_form_left, bin_form_right);
											break;
										case "^":
											formula = new PCSFC_Xor(bin_form_left, bin_form_right);
											break;
										default:
											formula = new PCSFC_And(bin_form_left, bin_form_right);
									}
									RESULT = formula;
								
              CUP$PCSFCConsoleParser$result = parser.getSymbolFactory().newSymbol("BINARY_FORMULA",18, ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.elementAt(CUP$PCSFCConsoleParser$top-4)), ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.peek()), RESULT);
            }
          return CUP$PCSFCConsoleParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // BINARY_FORMULA ::= BINARY_FORMULA BINARY_FORMULA_OPERATOR NEGATIVE_FORMULA_SYMBOL BINARY_FORMULA 
            {
              Formula<RevisorConsolePCSFC,PCSFCFormula> RESULT =null;
		int bin_form_leftleft = ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.elementAt(CUP$PCSFCConsoleParser$top-3)).left;
		int bin_form_leftright = ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.elementAt(CUP$PCSFCConsoleParser$top-3)).right;
		Formula<RevisorConsolePCSFC,PCSFCFormula> bin_form_left = (Formula<RevisorConsolePCSFC,PCSFCFormula>)((java_cup.runtime.Symbol) CUP$PCSFCConsoleParser$stack.elementAt(CUP$PCSFCConsoleParser$top-3)).value;
		int opleft = ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.elementAt(CUP$PCSFCConsoleParser$top-2)).left;
		int opright = ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.elementAt(CUP$PCSFCConsoleParser$top-2)).right;
		String op = (String)((java_cup.runtime.Symbol) CUP$PCSFCConsoleParser$stack.elementAt(CUP$PCSFCConsoleParser$top-2)).value;
		int bin_form_rightleft = ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.peek()).left;
		int bin_form_rightright = ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.peek()).right;
		Formula<RevisorConsolePCSFC,PCSFCFormula> bin_form_right = (Formula<RevisorConsolePCSFC,PCSFCFormula>)((java_cup.runtime.Symbol) CUP$PCSFCConsoleParser$stack.peek()).value;
		
									Formula<RevisorConsolePCSFC, PCSFCFormula> formula;
									switch (op) {
										case "&":
											formula = new PCSFC_And(bin_form_left, new PCSFC_Not(bin_form_right));
											break;
										case "|":
											formula = new PCSFC_Or(bin_form_left, new PCSFC_Not(bin_form_right));
											break;
										case "=>":
											formula = new PCSFC_Impl(bin_form_left, new PCSFC_Not(bin_form_right));
											break;
										case "<=>":
											formula = new PCSFC_Equiv(bin_form_left, new PCSFC_Not(bin_form_right));
											break;
										case "^":
											formula = new PCSFC_Xor(bin_form_left, new PCSFC_Not(bin_form_right));
											break;
										default:
											formula = new PCSFC_And(bin_form_left, new PCSFC_Not(bin_form_right));
									}
									RESULT = formula;
								
              CUP$PCSFCConsoleParser$result = parser.getSymbolFactory().newSymbol("BINARY_FORMULA",18, ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.elementAt(CUP$PCSFCConsoleParser$top-3)), ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.peek()), RESULT);
            }
          return CUP$PCSFCConsoleParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // BINARY_FORMULA ::= UNARY_FORMULA 
            {
              Formula<RevisorConsolePCSFC,PCSFCFormula> RESULT =null;
		int un_formleft = ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.peek()).left;
		int un_formright = ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.peek()).right;
		Formula<RevisorConsolePCSFC,PCSFCFormula> un_form = (Formula<RevisorConsolePCSFC,PCSFCFormula>)((java_cup.runtime.Symbol) CUP$PCSFCConsoleParser$stack.peek()).value;
		
									RESULT = un_form;
								
              CUP$PCSFCConsoleParser$result = parser.getSymbolFactory().newSymbol("BINARY_FORMULA",18, ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.peek()), RESULT);
            }
          return CUP$PCSFCConsoleParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // UNARY_FORMULA ::= CONSTRAINT_FORMULA 
            {
              Formula<RevisorConsolePCSFC,PCSFCFormula> RESULT =null;
		int cfleft = ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.peek()).left;
		int cfright = ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.peek()).right;
		Formula<RevisorConsolePCSFC,PCSFCFormula> cf = (Formula<RevisorConsolePCSFC,PCSFCFormula>)((java_cup.runtime.Symbol) CUP$PCSFCConsoleParser$stack.peek()).value;
		
									RESULT = cf;
								
              CUP$PCSFCConsoleParser$result = parser.getSymbolFactory().newSymbol("UNARY_FORMULA",19, ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.peek()), RESULT);
            }
          return CUP$PCSFCConsoleParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // UNARY_FORMULA ::= IDENTIFIER SIMPLE_EQUAL MODALITY 
            {
              Formula<RevisorConsolePCSFC,PCSFCFormula> RESULT =null;
		int idfleft = ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.elementAt(CUP$PCSFCConsoleParser$top-2)).left;
		int idfright = ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.elementAt(CUP$PCSFCConsoleParser$top-2)).right;
		String idf = (String)((java_cup.runtime.Symbol) CUP$PCSFCConsoleParser$stack.elementAt(CUP$PCSFCConsoleParser$top-2)).value;
		int modleft = ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.peek()).left;
		int modright = ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.peek()).right;
		String mod = (String)((java_cup.runtime.Symbol) CUP$PCSFCConsoleParser$stack.peek()).value;
		
									RESULT = new PCSFC_EnumIdentifierLitteral<RevisorConsolePCSFC>(new PCSFC_Identifier<RevisorConsolePCSFC>(idf), mod);
								
              CUP$PCSFCConsoleParser$result = parser.getSymbolFactory().newSymbol("UNARY_FORMULA",19, ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.elementAt(CUP$PCSFCConsoleParser$top-2)), ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.peek()), RESULT);
            }
          return CUP$PCSFCConsoleParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // UNARY_FORMULA ::= IDENTIFIER 
            {
              Formula<RevisorConsolePCSFC,PCSFCFormula> RESULT =null;
		int idfleft = ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.peek()).left;
		int idfright = ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.peek()).right;
		String idf = (String)((java_cup.runtime.Symbol) CUP$PCSFCConsoleParser$stack.peek()).value;
		
									RESULT = new PCSFC_IdentifierLitteral<RevisorConsolePCSFC>(new PCSFC_Identifier<RevisorConsolePCSFC>(idf));
								
              CUP$PCSFCConsoleParser$result = parser.getSymbolFactory().newSymbol("UNARY_FORMULA",19, ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.peek()), RESULT);
            }
          return CUP$PCSFCConsoleParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // UNARY_FORMULA ::= TAUTOLOGY_FORMULA 
            {
              Formula<RevisorConsolePCSFC,PCSFCFormula> RESULT =null;
		
									RESULT = new PCSFC_TautologyLitteral<RevisorConsolePCSFC>();
								
              CUP$PCSFCConsoleParser$result = parser.getSymbolFactory().newSymbol("UNARY_FORMULA",19, ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.peek()), RESULT);
            }
          return CUP$PCSFCConsoleParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // CONSTRAINT_FORMULA ::= CONSTRAINT_LEFT_MEMBER CONSTRAINT_OPERATOR CONSTRAINT_RIGHT_MEMBER 
            {
              Formula<RevisorConsolePCSFC,PCSFCFormula> RESULT =null;
		int leftleft = ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.elementAt(CUP$PCSFCConsoleParser$top-2)).left;
		int leftright = ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.elementAt(CUP$PCSFCConsoleParser$top-2)).right;
		LeftMember left = (LeftMember)((java_cup.runtime.Symbol) CUP$PCSFCConsoleParser$stack.elementAt(CUP$PCSFCConsoleParser$top-2)).value;
		int coleft = ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.elementAt(CUP$PCSFCConsoleParser$top-1)).left;
		int coright = ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.elementAt(CUP$PCSFCConsoleParser$top-1)).right;
		String co = (String)((java_cup.runtime.Symbol) CUP$PCSFCConsoleParser$stack.elementAt(CUP$PCSFCConsoleParser$top-1)).value;
		int rightleft = ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.peek()).left;
		int rightright = ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.peek()).right;
		RightMember<Double> right = (RightMember<Double>)((java_cup.runtime.Symbol) CUP$PCSFCConsoleParser$stack.peek()).value;
		
									ConstraintOperator operator;
									switch (co) {
										case "<=":
											operator = new ConstraintOperatorLessEquals();
											break;
										case "<":
											operator = new ConstraintOperatorLess();
											break;
										case ">=":
											operator = new ConstraintOperatorMoreEquals();
											break;
										case ">":
											operator = new ConstraintOperatorMore();
											break;
										case "!=":
											operator = new ConstraintOperatorNotEquals();
											break;
										case "==":
											operator = new ConstraintOperatorEquals();
											break;
										default:
											operator = new ConstraintOperatorMore();
									}
									RESULT = new PCSFC_ConstraintLitteral<RevisorConsolePCSFC>(left, operator, right);
								
              CUP$PCSFCConsoleParser$result = parser.getSymbolFactory().newSymbol("CONSTRAINT_FORMULA",20, ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.elementAt(CUP$PCSFCConsoleParser$top-2)), ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.peek()), RESULT);
            }
          return CUP$PCSFCConsoleParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // CONSTRAINT_LEFT_MEMBER ::= CONSTRAINT_TERM_LIST 
            {
              LeftMember RESULT =null;
		int ctlleft = ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.peek()).left;
		int ctlright = ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.peek()).right;
		LeftMember ctl = (LeftMember)((java_cup.runtime.Symbol) CUP$PCSFCConsoleParser$stack.peek()).value;
		
									RESULT = ctl;
								
              CUP$PCSFCConsoleParser$result = parser.getSymbolFactory().newSymbol("CONSTRAINT_LEFT_MEMBER",21, ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.peek()), RESULT);
            }
          return CUP$PCSFCConsoleParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // CONSTRAINT_TERM_LIST ::= CONSTRAINT_TERM_LIST CONSTRAINT_TERM_OPERATOR CONSTRAINT_TERM 
            {
              LeftMember RESULT =null;
		int ctlleft = ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.elementAt(CUP$PCSFCConsoleParser$top-2)).left;
		int ctlright = ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.elementAt(CUP$PCSFCConsoleParser$top-2)).right;
		LeftMember ctl = (LeftMember)((java_cup.runtime.Symbol) CUP$PCSFCConsoleParser$stack.elementAt(CUP$PCSFCConsoleParser$top-2)).value;
		int operleft = ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.elementAt(CUP$PCSFCConsoleParser$top-1)).left;
		int operright = ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.elementAt(CUP$PCSFCConsoleParser$top-1)).right;
		String oper = (String)((java_cup.runtime.Symbol) CUP$PCSFCConsoleParser$stack.elementAt(CUP$PCSFCConsoleParser$top-1)).value;
		int termleft = ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.peek()).left;
		int termright = ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.peek()).right;
		LeftMemberElementTerminal<Double,RevisorConsolePCSFC> term = (LeftMemberElementTerminal<Double,RevisorConsolePCSFC>)((java_cup.runtime.Symbol) CUP$PCSFCConsoleParser$stack.peek()).value;
		
									LeftMemberArithmeticOperator operator;
									switch (oper) {
										case "+":
											operator = new LeftMemberArithmeticOperatorAdd();
											break;
										case "-":
											operator = new LeftMemberArithmeticOperatorSub();
											break;
										default:
											operator = new LeftMemberArithmeticOperatorAdd();
									}
									RESULT = new LeftMemberElement(ctl, operator, term);
								
              CUP$PCSFCConsoleParser$result = parser.getSymbolFactory().newSymbol("CONSTRAINT_TERM_LIST",22, ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.elementAt(CUP$PCSFCConsoleParser$top-2)), ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.peek()), RESULT);
            }
          return CUP$PCSFCConsoleParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // CONSTRAINT_TERM_LIST ::= CONSTRAINT_TERM 
            {
              LeftMember RESULT =null;
		int termleft = ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.peek()).left;
		int termright = ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.peek()).right;
		LeftMemberElementTerminal<Double,RevisorConsolePCSFC> term = (LeftMemberElementTerminal<Double,RevisorConsolePCSFC>)((java_cup.runtime.Symbol) CUP$PCSFCConsoleParser$stack.peek()).value;
		
									RESULT = term;
								
              CUP$PCSFCConsoleParser$result = parser.getSymbolFactory().newSymbol("CONSTRAINT_TERM_LIST",22, ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.peek()), RESULT);
            }
          return CUP$PCSFCConsoleParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // CONSTRAINT_TERM ::= REAL IDENTIFIER 
            {
              LeftMemberElementTerminal<Double,RevisorConsolePCSFC> RESULT =null;
		int realleft = ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.elementAt(CUP$PCSFCConsoleParser$top-1)).left;
		int realright = ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.elementAt(CUP$PCSFCConsoleParser$top-1)).right;
		String real = (String)((java_cup.runtime.Symbol) CUP$PCSFCConsoleParser$stack.elementAt(CUP$PCSFCConsoleParser$top-1)).value;
		int idfleft = ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.peek()).left;
		int idfright = ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.peek()).right;
		String idf = (String)((java_cup.runtime.Symbol) CUP$PCSFCConsoleParser$stack.peek()).value;
		
									if (real.equals("-")) {
										RESULT = new LeftMemberElementTerminal<Double, RevisorConsolePCSFC>(-1.00, new PCSFC_Identifier<RevisorConsolePCSFC>(idf));
									}
									else {
										RESULT = new LeftMemberElementTerminal<Double, RevisorConsolePCSFC>(Double.parseDouble(real), new PCSFC_Identifier<RevisorConsolePCSFC>(idf));
									}
								
              CUP$PCSFCConsoleParser$result = parser.getSymbolFactory().newSymbol("CONSTRAINT_TERM",23, ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.elementAt(CUP$PCSFCConsoleParser$top-1)), ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.peek()), RESULT);
            }
          return CUP$PCSFCConsoleParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 52: // CONSTRAINT_TERM ::= IDENTIFIER 
            {
              LeftMemberElementTerminal<Double,RevisorConsolePCSFC> RESULT =null;
		int idfleft = ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.peek()).left;
		int idfright = ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.peek()).right;
		String idf = (String)((java_cup.runtime.Symbol) CUP$PCSFCConsoleParser$stack.peek()).value;
		
									RESULT = new LeftMemberElementTerminal<Double, RevisorConsolePCSFC>((double)1, new PCSFC_Identifier<RevisorConsolePCSFC>(idf));
								
              CUP$PCSFCConsoleParser$result = parser.getSymbolFactory().newSymbol("CONSTRAINT_TERM",23, ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.peek()), RESULT);
            }
          return CUP$PCSFCConsoleParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 53: // CONSTRAINT_RIGHT_MEMBER ::= REAL 
            {
              RightMember<Double> RESULT =null;
		int realleft = ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.peek()).left;
		int realright = ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.peek()).right;
		String real = (String)((java_cup.runtime.Symbol) CUP$PCSFCConsoleParser$stack.peek()).value;
		
									double d = Double.parseDouble(real);
									RESULT = new RightMember<Double>(d);
								
              CUP$PCSFCConsoleParser$result = parser.getSymbolFactory().newSymbol("CONSTRAINT_RIGHT_MEMBER",24, ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$PCSFCConsoleParser$stack.peek()), RESULT);
            }
          return CUP$PCSFCConsoleParser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$PCSFCConsoleParser$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$PCSFCConsoleParser$do_action(
    int                        CUP$PCSFCConsoleParser$act_num,
    java_cup.runtime.lr_parser CUP$PCSFCConsoleParser$parser,
    java.util.Stack            CUP$PCSFCConsoleParser$stack,
    int                        CUP$PCSFCConsoleParser$top)
    throws java.lang.Exception
    {
              return CUP$PCSFCConsoleParser$do_action_part00000000(
                               CUP$PCSFCConsoleParser$act_num,
                               CUP$PCSFCConsoleParser$parser,
                               CUP$PCSFCConsoleParser$stack,
                               CUP$PCSFCConsoleParser$top);
    }
}

}
