
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package fr.loria.k.revisor.engine.revisorPCSFC.console.parser;

/** CUP generated class containing symbol constants. */
public class PCSFCConsoleSymbols {
  /* terminals */
  public static final int FILE = 3;
  public static final int CLEAR = 4;
  public static final int COLON = 5;
  public static final int END_OF_INSTRUCTION = 7;
  public static final int REAL_DECLARATION_KEYWORD = 11;
  public static final int CONST_DECLARATION_KEYWORD = 13;
  public static final int EOF = 0;
  public static final int CONST_INITIALIZER_OPERATOR = 9;
  public static final int REAL = 14;
  public static final int error = 1;
  public static final int COMMA = 6;
  public static final int FORMULA_DECLARATION_KEYWORD = 12;
  public static final int INTEGER_DECLARATION_KEYWORD = 10;
  public static final int IDENTIFIER = 8;
  public static final int LOAD = 2;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "LOAD",
  "FILE",
  "CLEAR",
  "COLON",
  "COMMA",
  "END_OF_INSTRUCTION",
  "IDENTIFIER",
  "CONST_INITIALIZER_OPERATOR",
  "INTEGER_DECLARATION_KEYWORD",
  "REAL_DECLARATION_KEYWORD",
  "FORMULA_DECLARATION_KEYWORD",
  "CONST_DECLARATION_KEYWORD",
  "REAL"
  };
}

