/* The following code was generated by JFlex 1.5.0-SNAPSHOT */

package fr.loria.orpailleur.revisor.engine.revisorPL.console.parser;

import java_cup.runtime.Symbol;
import fr.loria.orpailleur.revisor.engine.core.console.exception.LexerException;

/**
 * This is the Revisor PL console lexer.
 * @author William Philbert
 */

public class PLConsoleLexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int FILE = 2;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1, 1
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\2\1\1\2\2\1\1\22\0\1\2\1\15\4\0\1\16"+
    "\1\0\1\12\1\13\2\0\1\14\1\7\1\5\1\0\1\4\11\3"+
    "\1\10\1\0\1\20\1\11\1\21\2\0\32\6\3\0\1\22\1\6"+
    "\1\0\1\30\1\6\1\32\1\31\1\24\1\42\1\40\1\23\1\37"+
    "\2\6\1\25\1\6\1\41\1\27\1\26\1\6\1\33\1\34\1\35"+
    "\1\44\1\43\1\36\3\6\1\0\1\17\10\0\1\2\32\0\1\2"+
    "\u15df\0\1\2\u097f\0\13\2\35\0\2\2\5\0\1\2\57\0\1\2"+
    "\u0fa0\0\1\2\ucfff\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\1\1\1\2\2\3\1\4\1\5\2\1\1\6"+
    "\1\7\1\10\1\11\1\12\1\13\1\1\1\14\11\5"+
    "\1\15\1\3\1\16\1\17\1\0\11\5\1\0\1\20"+
    "\3\5\1\21\6\5\1\22\1\23\4\5\1\24\2\5"+
    "\1\25\1\26\1\27\2\5\1\30\1\31\1\32\1\33";

  private static int [] zzUnpackAction() {
    int [] result = new int[71];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\45\0\112\0\112\0\157\0\224\0\271\0\336"+
    "\0\u0103\0\u0128\0\112\0\112\0\112\0\112\0\112\0\112"+
    "\0\u014d\0\112\0\u0172\0\u0197\0\u01bc\0\u01e1\0\u0206\0\u022b"+
    "\0\u0250\0\u0275\0\u029a\0\u02bf\0\271\0\112\0\112\0\u02e4"+
    "\0\u0309\0\u032e\0\u0353\0\u0378\0\u039d\0\u03c2\0\u03e7\0\u040c"+
    "\0\u0431\0\u02bf\0\112\0\u0456\0\u047b\0\u04a0\0\336\0\u04c5"+
    "\0\u04ea\0\u050f\0\u0534\0\u0559\0\u057e\0\336\0\336\0\u05a3"+
    "\0\u05c8\0\u05ed\0\u0612\0\336\0\u0637\0\u065c\0\336\0\336"+
    "\0\336\0\u0681\0\u06a6\0\336\0\336\0\u06cb\0\336";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[71];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\3\2\4\1\5\1\6\1\7\1\10\1\3\1\11"+
    "\1\12\1\13\1\14\1\15\1\16\1\17\1\20\1\21"+
    "\1\3\1\22\1\23\1\10\1\24\2\10\1\25\1\26"+
    "\1\27\1\30\1\10\1\31\1\32\3\10\1\33\2\10"+
    "\1\34\2\4\42\34\50\0\2\5\1\35\44\0\1\35"+
    "\42\0\2\35\43\0\2\10\1\0\2\10\13\0\22\10"+
    "\11\0\1\36\54\0\1\37\34\0\1\40\36\0\2\10"+
    "\1\0\2\10\13\0\1\10\1\41\20\10\3\0\2\10"+
    "\1\0\2\10\13\0\4\10\1\42\15\10\3\0\2\10"+
    "\1\0\2\10\13\0\6\10\1\43\13\10\3\0\2\10"+
    "\1\0\2\10\13\0\16\10\1\44\3\10\3\0\2\10"+
    "\1\0\2\10\13\0\2\10\1\45\17\10\3\0\2\10"+
    "\1\0\2\10\13\0\1\10\1\46\20\10\3\0\2\10"+
    "\1\0\2\10\13\0\10\10\1\47\11\10\3\0\2\10"+
    "\1\0\2\10\13\0\1\10\1\50\20\10\3\0\2\10"+
    "\1\0\2\10\13\0\5\10\1\51\14\10\1\34\1\0"+
    "\1\52\42\34\21\0\1\53\26\0\2\10\1\0\2\10"+
    "\13\0\2\10\1\54\17\10\3\0\2\10\1\0\2\10"+
    "\13\0\5\10\1\55\14\10\3\0\2\10\1\0\2\10"+
    "\13\0\5\10\1\56\14\10\3\0\2\10\1\0\2\10"+
    "\13\0\17\10\1\57\2\10\3\0\2\10\1\0\2\10"+
    "\13\0\1\10\1\60\20\10\3\0\2\10\1\0\2\10"+
    "\13\0\11\10\1\61\6\10\1\62\1\10\3\0\2\10"+
    "\1\0\2\10\13\0\21\10\1\63\3\0\2\10\1\0"+
    "\2\10\13\0\14\10\1\64\5\10\3\0\2\10\1\0"+
    "\2\10\13\0\2\10\1\65\17\10\3\0\2\10\1\0"+
    "\2\10\13\0\3\10\1\66\16\10\3\0\2\10\1\0"+
    "\2\10\13\0\6\10\1\67\13\10\3\0\2\10\1\0"+
    "\2\10\13\0\3\10\1\70\16\10\3\0\2\10\1\0"+
    "\2\10\13\0\5\10\1\71\14\10\3\0\2\10\1\0"+
    "\2\10\13\0\1\10\1\72\20\10\3\0\2\10\1\0"+
    "\2\10\13\0\14\10\1\73\5\10\3\0\2\10\1\0"+
    "\2\10\13\0\1\10\1\74\20\10\3\0\2\10\1\0"+
    "\2\10\13\0\15\10\1\75\4\10\3\0\2\10\1\0"+
    "\2\10\13\0\11\10\1\76\10\10\3\0\2\10\1\0"+
    "\2\10\13\0\12\10\1\77\7\10\3\0\2\10\1\0"+
    "\2\10\13\0\10\10\1\100\11\10\3\0\2\10\1\0"+
    "\2\10\13\0\12\10\1\101\7\10\3\0\2\10\1\0"+
    "\2\10\13\0\11\10\1\102\10\10\3\0\2\10\1\0"+
    "\2\10\13\0\1\103\21\10\3\0\2\10\1\0\2\10"+
    "\13\0\1\10\1\104\20\10\3\0\2\10\1\0\2\10"+
    "\13\0\1\10\1\105\20\10\3\0\2\10\1\0\2\10"+
    "\13\0\12\10\1\106\7\10\3\0\2\10\1\0\2\10"+
    "\13\0\11\10\1\107\10\10";

  private static int [] zzUnpackTrans() {
    int [] result = new int[1776];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\2\11\6\1\6\11\1\1\1\11\13\1\2\11"+
    "\1\0\11\1\1\0\1\11\34\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[71];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
  StringBuffer string = new StringBuffer();
  
  private Symbol symbol(int type) {
	return new Symbol(type, this.yyline, this.yycolumn);
  }

  private Symbol symbol(int type, Object value) {
	return new Symbol(type, this.yyline, this.yycolumn, value);
  }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public PLConsoleLexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 146) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

    // numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public Symbol next_token() throws java.io.IOException, LexerException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 1: 
          { throw new LexerException("Illegal character '" + yytext() + "'.");
          }
        case 28: break;
        case 2: 
          { /* Just skip what was found, do nothing */
          }
        case 29: break;
        case 3: 
          { return symbol(PLConsoleSymbols.POSITIVE_REAL, new Double(yytext()));
          }
        case 30: break;
        case 4: 
          { return symbol(PLConsoleSymbols.DOT);
          }
        case 31: break;
        case 5: 
          { return symbol(PLConsoleSymbols.IDENTIFIER, yytext());
          }
        case 32: break;
        case 6: 
          { return symbol(PLConsoleSymbols.L_PAR);
          }
        case 33: break;
        case 7: 
          { return symbol(PLConsoleSymbols.R_PAR);
          }
        case 34: break;
        case 8: 
          { return symbol(PLConsoleSymbols.COMMA);
          }
        case 35: break;
        case 9: 
          { return symbol(PLConsoleSymbols.NOT);
          }
        case 36: break;
        case 10: 
          { return symbol(PLConsoleSymbols.AND);
          }
        case 37: break;
        case 11: 
          { return symbol(PLConsoleSymbols.OR);
          }
        case 38: break;
        case 12: 
          { return symbol(PLConsoleSymbols.XOR);
          }
        case 39: break;
        case 13: 
          { return symbol(PLConsoleSymbols.FILE, yytext());
          }
        case 40: break;
        case 14: 
          { return symbol(PLConsoleSymbols.ASSIGN);
          }
        case 41: break;
        case 15: 
          { return symbol(PLConsoleSymbols.IMPL);
          }
        case 42: break;
        case 16: 
          { return symbol(PLConsoleSymbols.EQU);
          }
        case 43: break;
        case 17: 
          { return symbol(PLConsoleSymbols.DNF);
          }
        case 44: break;
        case 18: 
          { return symbol(PLConsoleSymbols.HELP);
          }
        case 45: break;
        case 19: 
          { yybegin(FILE); return symbol(PLConsoleSymbols.LOAD);
          }
        case 46: break;
        case 20: 
          { return symbol(PLConsoleSymbols.BOOLEAN, Boolean.TRUE);
          }
        case 47: break;
        case 21: 
          { return symbol(PLConsoleSymbols.ADAPT);
          }
        case 48: break;
        case 22: 
          { return symbol(PLConsoleSymbols.CLEAR);
          }
        case 49: break;
        case 23: 
          { return symbol(PLConsoleSymbols.RESET);
          }
        case 50: break;
        case 24: 
          { return symbol(PLConsoleSymbols.BOOLEAN, Boolean.FALSE);
          }
        case 51: break;
        case 25: 
          { return symbol(PLConsoleSymbols.REVISE);
          }
        case 52: break;
        case 26: 
          { return symbol(PLConsoleSymbols.WEIGHT);
          }
        case 53: break;
        case 27: 
          { return symbol(PLConsoleSymbols.WEIGHTS);
          }
        case 54: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              {     return symbol(PLConsoleSymbols.EOF);
 }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
