
//----------------------------------------------------
// The following code was generated by CUP v0.11a czt01 beta
// Wed Sep 24 17:45:57 CEST 2014
//----------------------------------------------------

package fr.loria.orpailleur.revisor.engine.revisorPL.console.parser;

/** CUP generated class containing symbol constants. */
public class PLConsoleSymbols {
  /* terminals */
  public static final int POSITIVE_REAL = 25;
  public static final int LOAD = 14;
  public static final int IMPL = 10;
  public static final int XOR = 12;
  public static final int R_PAR = 4;
  public static final int AND = 8;
  public static final int NOT = 7;
  public static final int WEIGHTS = 17;
  public static final int OR = 9;
  public static final int COMMA = 5;
  public static final int WEIGHT = 18;
  public static final int ASSIGN = 2;
  public static final int DOT = 6;
  public static final int REVISE = 21;
  public static final int BOOLEAN = 22;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int ADAPT = 20;
  public static final int EQU = 11;
  public static final int FILE = 24;
  public static final int CLEAR = 15;
  public static final int L_PAR = 3;
  public static final int RESET = 16;
  public static final int HELP = 13;
  public static final int DNF = 19;
  public static final int IDENTIFIER = 23;
}

