/* The following code was generated by JFlex 1.5.0-SNAPSHOT */

package fr.loria.orpailleur.revisor.engine.revisorPLAK.console.parser;

import java_cup.runtime.Symbol;
import fr.loria.orpailleur.revisor.engine.core.console.exception.LexerException;

/**
 * This is the Revisor PLAK console lexer.
 * @author William Philbert
 */

public class PLAKConsoleLexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int FILE = 2;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1, 1
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\2\1\1\2\2\1\1\22\0\1\2\1\24\4\0\1\25"+
    "\1\0\1\15\1\16\1\0\1\12\1\23\1\7\1\5\1\0\1\4"+
    "\11\3\1\10\1\0\1\27\1\11\1\14\2\0\32\6\1\21\1\0"+
    "\1\22\1\30\1\6\1\0\1\36\1\6\1\40\1\37\1\32\1\47"+
    "\1\46\1\31\1\45\2\6\1\33\1\6\1\51\1\35\1\34\1\6"+
    "\1\41\1\42\1\43\1\50\1\52\1\44\3\6\1\17\1\26\1\20"+
    "\1\13\6\0\1\2\32\0\1\2\u15df\0\1\2\u097f\0\13\2\35\0"+
    "\2\2\5\0\1\2\57\0\1\2\u0fa0\0\1\2\ucfff\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\1\1\1\2\2\3\1\4\1\5\1\1\1\6"+
    "\3\1\1\7\1\10\1\11\1\12\1\13\1\14\1\15"+
    "\1\16\1\17\1\20\1\1\1\21\12\5\1\22\1\3"+
    "\1\23\1\24\1\25\1\26\1\27\1\0\15\5\1\0"+
    "\1\30\4\5\1\31\10\5\1\32\1\33\1\34\6\5"+
    "\1\35\3\5\1\36\1\5\1\37\1\40\2\5\1\41"+
    "\2\5\1\42\1\5\1\43\2\5\1\44\1\5\1\45"+
    "\1\5\1\46\1\47\1\5\1\50\1\51\1\52\1\53"+
    "\1\54";

  private static int [] zzUnpackAction() {
    int [] result = new int[110];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\53\0\126\0\126\0\201\0\254\0\327\0\u0102"+
    "\0\u012d\0\u0158\0\u0183\0\u01ae\0\u01d9\0\126\0\126\0\126"+
    "\0\126\0\126\0\126\0\126\0\126\0\126\0\126\0\u0204"+
    "\0\126\0\u022f\0\u025a\0\u0285\0\u02b0\0\u02db\0\u0306\0\u0331"+
    "\0\u035c\0\u0387\0\u03b2\0\u03dd\0\327\0\126\0\126\0\126"+
    "\0\126\0\126\0\u0408\0\u0433\0\u045e\0\u0489\0\u04b4\0\u04df"+
    "\0\u050a\0\u0535\0\u0560\0\u058b\0\u05b6\0\u05e1\0\u060c\0\u0637"+
    "\0\u03dd\0\126\0\u0662\0\u068d\0\u06b8\0\u06e3\0\u0102\0\u070e"+
    "\0\u0739\0\u0764\0\u078f\0\u07ba\0\u07e5\0\u0810\0\u083b\0\u0102"+
    "\0\u0102\0\u0102\0\u0866\0\u0891\0\u08bc\0\u08e7\0\u0912\0\u093d"+
    "\0\u0102\0\u0968\0\u0993\0\u09be\0\u0102\0\u09e9\0\u0102\0\u0102"+
    "\0\u0a14\0\u0a3f\0\u0a6a\0\u0a95\0\u0ac0\0\u0102\0\u0aeb\0\u0102"+
    "\0\u0b16\0\u0b41\0\u0b6c\0\u0b97\0\u0102\0\u0bc2\0\u0bed\0\u0102"+
    "\0\u0c18\0\u0c43\0\u0102\0\u0c6e\0\u0102\0\u0102";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[110];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\3\2\4\1\5\1\6\1\7\1\10\1\11\1\12"+
    "\1\13\1\14\1\15\1\3\1\16\1\17\1\20\1\21"+
    "\1\22\1\23\1\24\1\25\1\26\1\27\1\30\1\31"+
    "\1\32\1\10\1\33\2\10\1\34\1\35\1\36\1\37"+
    "\1\10\1\40\1\41\2\10\1\42\1\43\2\10\1\44"+
    "\2\4\50\44\56\0\2\5\1\45\52\0\1\45\50\0"+
    "\2\45\51\0\2\10\1\0\2\10\21\0\22\10\11\0"+
    "\1\46\52\0\1\47\55\0\1\50\47\0\1\51\55\0"+
    "\1\52\47\0\1\53\44\0\2\10\1\0\2\10\21\0"+
    "\1\10\1\54\20\10\3\0\2\10\1\0\2\10\21\0"+
    "\4\10\1\55\15\10\3\0\2\10\1\0\2\10\21\0"+
    "\6\10\1\56\13\10\3\0\2\10\1\0\2\10\21\0"+
    "\1\10\1\57\16\10\1\60\1\10\3\0\2\10\1\0"+
    "\2\10\21\0\2\10\1\61\17\10\3\0\2\10\1\0"+
    "\2\10\21\0\1\10\1\62\15\10\1\63\2\10\3\0"+
    "\2\10\1\0\2\10\21\0\10\10\1\64\11\10\3\0"+
    "\2\10\1\0\2\10\21\0\1\10\1\65\20\10\3\0"+
    "\2\10\1\0\2\10\21\0\2\10\1\66\2\10\1\67"+
    "\14\10\3\0\2\10\1\0\2\10\21\0\11\10\1\70"+
    "\10\10\1\44\1\0\1\71\50\44\14\0\1\72\41\0"+
    "\2\10\1\0\2\10\21\0\2\10\1\73\17\10\3\0"+
    "\2\10\1\0\2\10\21\0\5\10\1\74\14\10\3\0"+
    "\2\10\1\0\2\10\21\0\5\10\1\75\14\10\3\0"+
    "\2\10\1\0\2\10\21\0\16\10\1\76\3\10\3\0"+
    "\2\10\1\0\2\10\21\0\16\10\1\77\3\10\3\0"+
    "\2\10\1\0\2\10\21\0\1\10\1\100\20\10\3\0"+
    "\2\10\1\0\2\10\21\0\11\10\1\101\7\10\1\102"+
    "\3\0\2\10\1\0\2\10\21\0\2\10\1\103\17\10"+
    "\3\0\2\10\1\0\2\10\21\0\17\10\1\104\2\10"+
    "\3\0\2\10\1\0\2\10\21\0\14\10\1\105\5\10"+
    "\3\0\2\10\1\0\2\10\21\0\14\10\1\106\5\10"+
    "\3\0\2\10\1\0\2\10\21\0\2\10\1\107\17\10"+
    "\3\0\2\10\1\0\2\10\21\0\1\10\1\110\20\10"+
    "\3\0\2\10\1\0\2\10\21\0\3\10\1\111\16\10"+
    "\3\0\2\10\1\0\2\10\21\0\6\10\1\112\13\10"+
    "\3\0\2\10\1\0\2\10\21\0\3\10\1\113\16\10"+
    "\3\0\2\10\1\0\2\10\21\0\5\10\1\114\14\10"+
    "\3\0\2\10\1\0\2\10\21\0\5\10\1\115\14\10"+
    "\3\0\2\10\1\0\2\10\21\0\1\10\1\116\20\10"+
    "\3\0\2\10\1\0\2\10\21\0\14\10\1\117\5\10"+
    "\3\0\2\10\1\0\2\10\21\0\1\10\1\120\20\10"+
    "\3\0\2\10\1\0\2\10\21\0\1\10\1\121\20\10"+
    "\3\0\2\10\1\0\2\10\21\0\15\10\1\122\4\10"+
    "\3\0\2\10\1\0\2\10\21\0\3\10\1\123\16\10"+
    "\3\0\2\10\1\0\2\10\21\0\11\10\1\124\10\10"+
    "\3\0\2\10\1\0\2\10\21\0\12\10\1\125\7\10"+
    "\3\0\2\10\1\0\2\10\21\0\17\10\1\126\2\10"+
    "\3\0\2\10\1\0\2\10\21\0\10\10\1\127\11\10"+
    "\3\0\2\10\1\0\2\10\21\0\12\10\1\130\7\10"+
    "\3\0\2\10\1\0\2\10\21\0\11\10\1\131\10\10"+
    "\3\0\2\10\1\0\2\10\21\0\7\10\1\132\1\10"+
    "\1\133\10\10\3\0\2\10\1\0\2\10\21\0\1\134"+
    "\21\10\3\0\2\10\1\0\2\10\21\0\7\10\1\135"+
    "\12\10\3\0\2\10\1\0\2\10\21\0\1\10\1\136"+
    "\20\10\3\0\2\10\1\0\2\10\21\0\2\10\1\137"+
    "\17\10\3\0\2\10\1\0\2\10\21\0\1\10\1\140"+
    "\20\10\3\0\2\10\1\0\2\10\21\0\4\10\1\141"+
    "\15\10\3\0\2\10\1\0\2\10\21\0\1\10\1\142"+
    "\20\10\3\0\2\10\1\0\2\10\21\0\12\10\1\143"+
    "\7\10\3\0\2\10\1\0\2\10\21\0\4\10\1\144"+
    "\15\10\3\0\2\10\1\0\2\10\21\0\12\10\1\145"+
    "\7\10\3\0\2\10\1\0\2\10\21\0\11\10\1\146"+
    "\10\10\3\0\2\10\1\0\2\10\21\0\12\10\1\147"+
    "\7\10\3\0\2\10\1\0\2\10\21\0\11\10\1\150"+
    "\10\10\3\0\2\10\1\0\2\10\21\0\11\10\1\151"+
    "\10\10\3\0\2\10\1\0\2\10\21\0\12\10\1\152"+
    "\7\10\3\0\2\10\1\0\2\10\21\0\11\10\1\153"+
    "\10\10\3\0\2\10\1\0\2\10\21\0\12\10\1\154"+
    "\7\10\3\0\2\10\1\0\2\10\21\0\11\10\1\155"+
    "\10\10\3\0\2\10\1\0\2\10\21\0\11\10\1\156"+
    "\10\10";

  private static int [] zzUnpackTrans() {
    int [] result = new int[3225];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\2\11\11\1\12\11\1\1\1\11\14\1\5\11"+
    "\1\0\15\1\1\0\1\11\64\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[110];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
  StringBuffer string = new StringBuffer();
  
  private Symbol symbol(int type) {
	return new Symbol(type, this.yyline, this.yycolumn);
  }

  private Symbol symbol(int type, Object value) {
	return new Symbol(type, this.yyline, this.yycolumn, value);
  }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public PLAKConsoleLexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 156) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

    // numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public Symbol next_token() throws java.io.IOException, LexerException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 1: 
          { throw new LexerException("Illegal character '" + yytext() + "'.");
          }
        case 45: break;
        case 2: 
          { /* Just skip what was found, do nothing */
          }
        case 46: break;
        case 3: 
          { return symbol(PLAKConsoleSymbols.POSITIVE_REAL, new Double(yytext()));
          }
        case 47: break;
        case 4: 
          { return symbol(PLAKConsoleSymbols.DOT);
          }
        case 48: break;
        case 5: 
          { return symbol(PLAKConsoleSymbols.IDENTIFIER, yytext());
          }
        case 49: break;
        case 6: 
          { return symbol(PLAKConsoleSymbols.COLON);
          }
        case 50: break;
        case 7: 
          { return symbol(PLAKConsoleSymbols.L_PAR);
          }
        case 51: break;
        case 8: 
          { return symbol(PLAKConsoleSymbols.R_PAR);
          }
        case 52: break;
        case 9: 
          { return symbol(PLAKConsoleSymbols.L_BRACE);
          }
        case 53: break;
        case 10: 
          { return symbol(PLAKConsoleSymbols.R_BRACE);
          }
        case 54: break;
        case 11: 
          { return symbol(PLAKConsoleSymbols.L_BRACKET);
          }
        case 55: break;
        case 12: 
          { return symbol(PLAKConsoleSymbols.R_BRACKET);
          }
        case 56: break;
        case 13: 
          { return symbol(PLAKConsoleSymbols.COMMA);
          }
        case 57: break;
        case 14: 
          { return symbol(PLAKConsoleSymbols.NOT);
          }
        case 58: break;
        case 15: 
          { return symbol(PLAKConsoleSymbols.AND);
          }
        case 59: break;
        case 16: 
          { return symbol(PLAKConsoleSymbols.OR);
          }
        case 60: break;
        case 17: 
          { return symbol(PLAKConsoleSymbols.XOR);
          }
        case 61: break;
        case 18: 
          { return symbol(PLAKConsoleSymbols.FILE, yytext());
          }
        case 62: break;
        case 19: 
          { return symbol(PLAKConsoleSymbols.REMOVE);
          }
        case 63: break;
        case 20: 
          { return symbol(PLAKConsoleSymbols.ASSIGN);
          }
        case 64: break;
        case 21: 
          { return symbol(PLAKConsoleSymbols.IMPL);
          }
        case 65: break;
        case 22: 
          { return symbol(PLAKConsoleSymbols.ADD);
          }
        case 66: break;
        case 23: 
          { return symbol(PLAKConsoleSymbols.REPLACE);
          }
        case 67: break;
        case 24: 
          { return symbol(PLAKConsoleSymbols.EQU);
          }
        case 68: break;
        case 25: 
          { return symbol(PLAKConsoleSymbols.DNF);
          }
        case 69: break;
        case 26: 
          { return symbol(PLAKConsoleSymbols.USE);
          }
        case 70: break;
        case 27: 
          { return symbol(PLAKConsoleSymbols.HELP);
          }
        case 71: break;
        case 28: 
          { yybegin(FILE); return symbol(PLAKConsoleSymbols.LOAD);
          }
        case 72: break;
        case 29: 
          { return symbol(PLAKConsoleSymbols.BOOLEAN, Boolean.TRUE);
          }
        case 73: break;
        case 30: 
          { return symbol(PLAKConsoleSymbols.ADAPT);
          }
        case 74: break;
        case 31: 
          { return symbol(PLAKConsoleSymbols.CLEAR);
          }
        case 75: break;
        case 32: 
          { return symbol(PLAKConsoleSymbols.RESET);
          }
        case 76: break;
        case 33: 
          { return symbol(PLAKConsoleSymbols.RULES);
          }
        case 77: break;
        case 34: 
          { return symbol(PLAKConsoleSymbols.BOOLEAN, Boolean.FALSE);
          }
        case 78: break;
        case 35: 
          { return symbol(PLAKConsoleSymbols.REVISE);
          }
        case 79: break;
        case 36: 
          { return symbol(PLAKConsoleSymbols.WEIGHT);
          }
        case 80: break;
        case 37: 
          { return symbol(PLAKConsoleSymbols.DEFAULT);
          }
        case 81: break;
        case 38: 
          { return symbol(PLAKConsoleSymbols.RULESET);
          }
        case 82: break;
        case 39: 
          { return symbol(PLAKConsoleSymbols.WEIGHTS);
          }
        case 83: break;
        case 40: 
          { return symbol(PLAKConsoleSymbols.RULECOST);
          }
        case 84: break;
        case 41: 
          { return symbol(PLAKConsoleSymbols.RULESETS);
          }
        case 85: break;
        case 42: 
          { return symbol(PLAKConsoleSymbols.FLIPCOST);
          }
        case 86: break;
        case 43: 
          { return symbol(PLAKConsoleSymbols.RULECOSTS);
          }
        case 87: break;
        case 44: 
          { return symbol(PLAKConsoleSymbols.FLIPCOSTS);
          }
        case 88: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              {     return symbol(PLAKConsoleSymbols.EOF);
 }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
