
//----------------------------------------------------
// The following code was generated by CUP v0.11a czt01 beta
// Wed Sep 24 17:45:58 CEST 2014
//----------------------------------------------------

package fr.loria.orpailleur.revisor.engine.revisorPLAK.console.parser;

/** CUP generated class containing symbol constants. */
public class PLAKConsoleSymbols {
  /* terminals */
  public static final int POSITIVE_REAL = 42;
  public static final int REMOVE = 4;
  public static final int LOAD = 22;
  public static final int IMPL = 18;
  public static final int XOR = 20;
  public static final int R_PAR = 10;
  public static final int RULES = 31;
  public static final int AND = 16;
  public static final int NOT = 15;
  public static final int USE = 34;
  public static final int RULECOST = 30;
  public static final int WEIGHTS = 25;
  public static final int OR = 17;
  public static final int COMMA = 6;
  public static final int WEIGHT = 26;
  public static final int ASSIGN = 2;
  public static final int FLIPCOSTS = 27;
  public static final int DOT = 7;
  public static final int REVISE = 38;
  public static final int R_BRACKET = 14;
  public static final int BOOLEAN = 39;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int ADD = 3;
  public static final int RULECOSTS = 29;
  public static final int RULESET = 33;
  public static final int ADAPT = 37;
  public static final int EQU = 19;
  public static final int L_BRACE = 11;
  public static final int COLON = 8;
  public static final int R_BRACE = 12;
  public static final int FILE = 41;
  public static final int RULESETS = 32;
  public static final int DEFAULT = 35;
  public static final int CLEAR = 23;
  public static final int FLIPCOST = 28;
  public static final int L_PAR = 9;
  public static final int RESET = 24;
  public static final int HELP = 21;
  public static final int L_BRACKET = 13;
  public static final int DNF = 36;
  public static final int REPLACE = 5;
  public static final int IDENTIFIER = 40;
}

